/* commentconverter.c generated by balac, the Bala compiler
 * generated from commentconverter.bala, do not modify */

/* commentconverter.bala
 *
 * Copyright (C) 2010 Luca Bruno
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Luca Bruno <lethalman88@gmail.com>
 */

#include <baladoc.h>
#include <glib-object.h>
#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <balagee.h>
#include <float.h>
#include <math.h>

#define GTKDOC_TYPE_COMMENT_CONVERTER (gtkdoc_comment_converter_get_type ())
#define GTKDOC_COMMENT_CONVERTER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTKDOC_TYPE_COMMENT_CONVERTER, GtkdocCommentConverter))
#define GTKDOC_COMMENT_CONVERTER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GTKDOC_TYPE_COMMENT_CONVERTER, GtkdocCommentConverterClass))
#define GTKDOC_IS_COMMENT_CONVERTER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GTKDOC_TYPE_COMMENT_CONVERTER))
#define GTKDOC_IS_COMMENT_CONVERTER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GTKDOC_TYPE_COMMENT_CONVERTER))
#define GTKDOC_COMMENT_CONVERTER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GTKDOC_TYPE_COMMENT_CONVERTER, GtkdocCommentConverterClass))

typedef struct _GtkdocCommentConverter GtkdocCommentConverter;
typedef struct _GtkdocCommentConverterClass GtkdocCommentConverterClass;
typedef struct _GtkdocCommentConverterPrivate GtkdocCommentConverterPrivate;

#define GTKDOC_TYPE_HEADER (gtkdoc_header_get_type ())
#define GTKDOC_HEADER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), GTKDOC_TYPE_HEADER, GtkdocHeader))
#define GTKDOC_HEADER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), GTKDOC_TYPE_HEADER, GtkdocHeaderClass))
#define GTKDOC_IS_HEADER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), GTKDOC_TYPE_HEADER))
#define GTKDOC_IS_HEADER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), GTKDOC_TYPE_HEADER))
#define GTKDOC_HEADER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), GTKDOC_TYPE_HEADER, GtkdocHeaderClass))

typedef struct _GtkdocHeader GtkdocHeader;
typedef struct _GtkdocHeaderClass GtkdocHeaderClass;
enum  {
	GTKDOC_COMMENT_CONVERTER_0_PROPERTY,
	GTKDOC_COMMENT_CONVERTER_NUM_PROPERTIES
};
static GParamSpec* gtkdoc_comment_converter_properties[GTKDOC_COMMENT_CONVERTER_NUM_PROPERTIES];
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _g_free0(var) (var = (g_free (var), NULL))
#define _bala_iterable_unref0(var) ((var == NULL) ? NULL : (var = (bala_iterable_unref (var), NULL)))
#define _g_string_free0(var) ((var == NULL) ? NULL : (var = (g_string_free (var, TRUE), NULL)))
#define _gtkdoc_header_unref0(var) ((var == NULL) ? NULL : (var = (gtkdoc_header_unref (var), NULL)))

struct _GtkdocCommentConverter {
	BaladocContentContentVisitor parent_instance;
	BaladocApiNode* node_reference;
	gboolean is_dbus;
	gchar* brief_comment;
	gchar* long_comment;
	gchar* returns;
	BalaList* parameters;
	BalaList* versioning;
	gchar** see_also;
	gint see_also_length1;
	GtkdocCommentConverterPrivate * priv;
};

struct _GtkdocCommentConverterClass {
	BaladocContentContentVisitorClass parent_class;
};

struct _GtkdocCommentConverterPrivate {
	GString* current_builder;
	gboolean in_brief_comment;
	BaladocErrorReporter* reporter;
};

static gint GtkdocCommentConverter_private_offset;
static gpointer gtkdoc_comment_converter_parent_class = NULL;

GType gtkdoc_comment_converter_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GtkdocCommentConverter, g_object_unref)
gpointer gtkdoc_header_ref (gpointer instance);
void gtkdoc_header_unref (gpointer instance);
GParamSpec* gtkdoc_param_spec_header (const gchar* name,
                                      const gchar* nick,
                                      const gchar* blurb,
                                      GType object_type,
                                      GParamFlags flags);
void gtkdoc_value_set_header (GValue* value,
                              gpointer v_object);
void gtkdoc_value_take_header (GValue* value,
                               gpointer v_object);
gpointer gtkdoc_value_get_header (const GValue* value);
GType gtkdoc_header_get_type (void) G_GNUC_CONST;
G_DEFINE_AUTOPTR_CLEANUP_FUNC (GtkdocHeader, gtkdoc_header_unref)
GtkdocCommentConverter* gtkdoc_comment_converter_new (BaladocErrorReporter* reporter,
                                                      BaladocApiNode* node_reference);
GtkdocCommentConverter* gtkdoc_comment_converter_construct (GType object_type,
                                                            BaladocErrorReporter* reporter,
                                                            BaladocApiNode* node_reference);
void gtkdoc_comment_converter_convert (GtkdocCommentConverter* self,
                                       BaladocContentComment* comment,
                                       gboolean is_dbus);
static void gtkdoc_comment_converter_real_visit_comment (BaladocContentContentVisitor* base,
                                                  BaladocContentComment* c);
static void gtkdoc_comment_converter_real_visit_embedded (BaladocContentContentVisitor* base,
                                                   BaladocContentEmbedded* em);
static void gtkdoc_comment_converter_real_visit_headline (BaladocContentContentVisitor* base,
                                                   BaladocContentHeadline* hl);
static void gtkdoc_comment_converter_real_visit_wiki_link (BaladocContentContentVisitor* base,
                                                    BaladocContentWikiLink* link);
static void gtkdoc_comment_converter_real_visit_link (BaladocContentContentVisitor* base,
                                               BaladocContentLink* link);
static void gtkdoc_comment_converter_real_visit_symbol_link (BaladocContentContentVisitor* base,
                                                      BaladocContentSymbolLink* sl);
gchar* gtkdoc_get_docbook_link (BaladocApiItem* item,
                                gboolean is_dbus,
                                gboolean is_async_finish);
static void gtkdoc_comment_converter_real_visit_list (BaladocContentContentVisitor* base,
                                               BaladocContentList* list);
static void gtkdoc_comment_converter_real_visit_list_item (BaladocContentContentVisitor* base,
                                                    BaladocContentListItem* item);
static void gtkdoc_comment_converter_real_visit_paragraph (BaladocContentContentVisitor* base,
                                                    BaladocContentParagraph* para);
static void gtkdoc_comment_converter_real_visit_warning (BaladocContentContentVisitor* base,
                                                  BaladocContentWarning* element);
static void gtkdoc_comment_converter_real_visit_note (BaladocContentContentVisitor* base,
                                               BaladocContentNote* element);
static void gtkdoc_comment_converter_real_visit_page (BaladocContentContentVisitor* base,
                                               BaladocContentPage* page);
static void gtkdoc_comment_converter_real_visit_run (BaladocContentContentVisitor* base,
                                              BaladocContentRun* run);
static void gtkdoc_comment_converter_real_visit_source_code (BaladocContentContentVisitor* base,
                                                      BaladocContentSourceCode* code);
static void gtkdoc_comment_converter_real_visit_table (BaladocContentContentVisitor* base,
                                                BaladocContentTable* t);
static void gtkdoc_comment_converter_real_visit_table_row (BaladocContentContentVisitor* base,
                                                    BaladocContentTableRow* row);
static void gtkdoc_comment_converter_real_visit_table_cell (BaladocContentContentVisitor* base,
                                                     BaladocContentTableCell* cell);
static void gtkdoc_comment_converter_real_visit_taglet (BaladocContentContentVisitor* base,
                                                 BaladocContentTaglet* t);
gdouble gtkdoc_get_parameter_pos (BaladocApiNode* node,
                                  const gchar* name);
GtkdocHeader* gtkdoc_header_new (const gchar* name,
                                 const gchar* value,
                                 gdouble pos,
                                 gboolean block);
GtkdocHeader* gtkdoc_header_construct (GType object_type,
                                       const gchar* name,
                                       const gchar* value,
                                       gdouble pos,
                                       gboolean block);
static gchar** _bala_array_dup1 (gchar** self,
                          gint length);
static void _bala_array_add1 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
static void _bala_array_add2 (gchar** * array,
                       gint* length,
                       gint* size,
                       gchar* value);
static gchar** _bala_array_dup2 (gchar** self,
                          gint length);
static void gtkdoc_comment_converter_real_visit_text (BaladocContentContentVisitor* base,
                                               BaladocContentText* t);
static void gtkdoc_comment_converter_finalize (GObject * obj);
static GType gtkdoc_comment_converter_get_type_once (void);
static void _bala_array_destroy (gpointer array,
                          gint array_length,
                          GDestroyNotify destroy_func);
static void _bala_array_free (gpointer array,
                       gint array_length,
                       GDestroyNotify destroy_func);

static inline gpointer
gtkdoc_comment_converter_get_instance_private (GtkdocCommentConverter* self)
{
	return G_STRUCT_MEMBER_P (self, GtkdocCommentConverter_private_offset);
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

GtkdocCommentConverter*
gtkdoc_comment_converter_construct (GType object_type,
                                    BaladocErrorReporter* reporter,
                                    BaladocApiNode* node_reference)
{
	GtkdocCommentConverter * self = NULL;
	BaladocApiNode* _tmp0_;
	BaladocErrorReporter* _tmp1_;
	g_return_val_if_fail (reporter != NULL, NULL);
	self = (GtkdocCommentConverter*) baladoc_content_content_visitor_construct (object_type);
	_tmp0_ = _g_object_ref0 (node_reference);
	_g_object_unref0 (self->node_reference);
	self->node_reference = _tmp0_;
	_tmp1_ = _g_object_ref0 (reporter);
	_g_object_unref0 (self->priv->reporter);
	self->priv->reporter = _tmp1_;
	return self;
}

GtkdocCommentConverter*
gtkdoc_comment_converter_new (BaladocErrorReporter* reporter,
                              BaladocApiNode* node_reference)
{
	return gtkdoc_comment_converter_construct (GTKDOC_TYPE_COMMENT_CONVERTER, reporter, node_reference);
}

static gchar*
string_strip (const gchar* self)
{
	gchar* _result_ = NULL;
	gchar* _tmp0_;
	gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = g_strdup (self);
	_result_ = _tmp0_;
	g_strstrip (_result_);
	result = _result_;
	return result;
}

void
gtkdoc_comment_converter_convert (GtkdocCommentConverter* self,
                                  BaladocContentComment* comment,
                                  gboolean is_dbus)
{
	GString* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	const gchar* _tmp3_;
	g_return_if_fail (self != NULL);
	g_return_if_fail (comment != NULL);
	self->is_dbus = is_dbus;
	baladoc_content_content_element_accept ((BaladocContentContentElement*) comment, (BaladocContentContentVisitor*) self);
	_tmp0_ = self->priv->current_builder;
	_tmp1_ = _tmp0_->str;
	_tmp2_ = string_strip (_tmp1_);
	_g_free0 (self->long_comment);
	self->long_comment = _tmp2_;
	_tmp3_ = self->long_comment;
	if (g_strcmp0 (_tmp3_, "") == 0) {
		_g_free0 (self->long_comment);
		self->long_comment = NULL;
	}
}

static void
gtkdoc_comment_converter_real_visit_comment (BaladocContentContentVisitor* base,
                                             BaladocContentComment* c)
{
	GtkdocCommentConverter * self;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (c != NULL);
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) c, (BaladocContentContentVisitor*) self);
}

static void
gtkdoc_comment_converter_real_visit_embedded (BaladocContentContentVisitor* base,
                                              BaladocContentEmbedded* em)
{
	GtkdocCommentConverter * self;
	GString* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	GString* _tmp6_;
	const gchar* _tmp7_;
	const gchar* _tmp8_;
	const gchar* _tmp9_;
	const gchar* _tmp10_;
	GString* _tmp14_;
	GString* _tmp15_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (em != NULL);
	_tmp0_ = self->priv->current_builder;
	g_string_append (_tmp0_, "<figure>");
	_tmp1_ = baladoc_content_embedded_get_caption (em);
	_tmp2_ = _tmp1_;
	if (_tmp2_ != NULL) {
		GString* _tmp3_;
		const gchar* _tmp4_;
		const gchar* _tmp5_;
		_tmp3_ = self->priv->current_builder;
		_tmp4_ = baladoc_content_embedded_get_caption (em);
		_tmp5_ = _tmp4_;
		g_string_append_printf (_tmp3_, "<title>%s</title>", _tmp5_);
	}
	_tmp6_ = self->priv->current_builder;
	_tmp7_ = baladoc_content_embedded_get_url (em);
	_tmp8_ = _tmp7_;
	g_string_append_printf (_tmp6_, "<mediaobject><imageobject><imagedata fileref=\"%s\"/></imageobject>", _tmp8_);
	_tmp9_ = baladoc_content_embedded_get_caption (em);
	_tmp10_ = _tmp9_;
	if (_tmp10_ != NULL) {
		GString* _tmp11_;
		const gchar* _tmp12_;
		const gchar* _tmp13_;
		_tmp11_ = self->priv->current_builder;
		_tmp12_ = baladoc_content_embedded_get_caption (em);
		_tmp13_ = _tmp12_;
		g_string_append_printf (_tmp11_, "<textobject><phrase>%s</phrase></textobject>", _tmp13_);
	}
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) em, (BaladocContentContentVisitor*) self);
	_tmp14_ = self->priv->current_builder;
	g_string_append (_tmp14_, "</mediaobject>");
	_tmp15_ = self->priv->current_builder;
	g_string_append (_tmp15_, "</figure>");
}

static void
gtkdoc_comment_converter_real_visit_headline (BaladocContentContentVisitor* base,
                                              BaladocContentHeadline* hl)
{
	GtkdocCommentConverter * self;
	BaladocErrorReporter* _tmp0_;
	GString* _tmp1_;
	GString* _tmp2_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (hl != NULL);
	_tmp0_ = self->priv->reporter;
	baladoc_error_reporter_simple_warning (_tmp0_, "GtkDoc", "Headline elements not supported");
	_tmp1_ = self->priv->current_builder;
	g_string_append (_tmp1_, "\n");
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) hl, (BaladocContentContentVisitor*) self);
	_tmp2_ = self->priv->current_builder;
	g_string_append (_tmp2_, "\n");
}

static void
gtkdoc_comment_converter_real_visit_wiki_link (BaladocContentContentVisitor* base,
                                               BaladocContentWikiLink* link)
{
	GtkdocCommentConverter * self;
	BalaList* _tmp0_;
	BalaList* _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (link != NULL);
	_tmp0_ = baladoc_content_inline_content_get_content ((BaladocContentInlineContent*) link);
	_tmp1_ = _tmp0_;
	_tmp2_ = bala_collection_get_size ((BalaCollection*) _tmp1_);
	_tmp3_ = _tmp2_;
	if (_tmp3_ > 0) {
		baladoc_content_content_element_accept_children ((BaladocContentContentElement*) link, (BaladocContentContentVisitor*) self);
	} else {
		GString* _tmp4_;
		const gchar* _tmp5_;
		const gchar* _tmp6_;
		_tmp4_ = self->priv->current_builder;
		_tmp5_ = baladoc_content_wiki_link_get_name (link);
		_tmp6_ = _tmp5_;
		g_string_append (_tmp4_, _tmp6_);
	}
}

static void
gtkdoc_comment_converter_real_visit_link (BaladocContentContentVisitor* base,
                                          BaladocContentLink* link)
{
	GtkdocCommentConverter * self;
	GString* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	GString* _tmp3_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (link != NULL);
	_tmp0_ = self->priv->current_builder;
	_tmp1_ = baladoc_content_link_get_url (link);
	_tmp2_ = _tmp1_;
	g_string_append_printf (_tmp0_, "<ulink url=\"%s\">", _tmp2_);
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) link, (BaladocContentContentVisitor*) self);
	_tmp3_ = self->priv->current_builder;
	g_string_append (_tmp3_, "</ulink>");
}

static void
gtkdoc_comment_converter_real_visit_symbol_link (BaladocContentContentVisitor* base,
                                                 BaladocContentSymbolLink* sl)
{
	GtkdocCommentConverter * self;
	BaladocApiNode* _tmp0_;
	BaladocApiNode* _tmp1_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (sl != NULL);
	_tmp0_ = baladoc_content_symbol_link_get_symbol (sl);
	_tmp1_ = _tmp0_;
	if (_tmp1_ != NULL) {
		gboolean _tmp2_ = FALSE;
		gboolean _tmp3_ = FALSE;
		gboolean _tmp4_ = FALSE;
		BaladocApiNode* _tmp5_;
		BaladocApiNode* _tmp6_;
		_tmp5_ = baladoc_content_symbol_link_get_symbol (sl);
		_tmp6_ = _tmp5_;
		if (G_TYPE_CHECK_INSTANCE_TYPE (_tmp6_, BALADOC_API_TYPE_METHOD)) {
			BaladocApiNode* _tmp7_;
			BaladocApiNode* _tmp8_;
			gboolean _tmp9_;
			gboolean _tmp10_;
			_tmp7_ = baladoc_content_symbol_link_get_symbol (sl);
			_tmp8_ = _tmp7_;
			_tmp9_ = baladoc_api_method_get_is_constructor (G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, BALADOC_API_TYPE_METHOD, BaladocApiMethod));
			_tmp10_ = _tmp9_;
			_tmp4_ = _tmp10_;
		} else {
			_tmp4_ = FALSE;
		}
		if (_tmp4_) {
			BaladocApiNode* _tmp11_;
			BaladocApiNode* _tmp12_;
			BaladocApiItem* _tmp13_;
			BaladocApiItem* _tmp14_;
			_tmp11_ = baladoc_content_symbol_link_get_symbol (sl);
			_tmp12_ = _tmp11_;
			_tmp13_ = baladoc_api_item_get_parent ((BaladocApiItem*) G_TYPE_CHECK_INSTANCE_CAST (_tmp12_, BALADOC_API_TYPE_METHOD, BaladocApiMethod));
			_tmp14_ = _tmp13_;
			_tmp3_ = G_TYPE_CHECK_INSTANCE_TYPE (_tmp14_, BALADOC_API_TYPE_CLASS);
		} else {
			_tmp3_ = FALSE;
		}
		if (_tmp3_) {
			BaladocApiNode* _tmp15_;
			BaladocApiNode* _tmp16_;
			BaladocApiItem* _tmp17_;
			BaladocApiItem* _tmp18_;
			gboolean _tmp19_;
			gboolean _tmp20_;
			_tmp15_ = baladoc_content_symbol_link_get_symbol (sl);
			_tmp16_ = _tmp15_;
			_tmp17_ = baladoc_api_item_get_parent ((BaladocApiItem*) G_TYPE_CHECK_INSTANCE_CAST (_tmp16_, BALADOC_API_TYPE_METHOD, BaladocApiMethod));
			_tmp18_ = _tmp17_;
			_tmp19_ = baladoc_api_class_get_is_abstract (G_TYPE_CHECK_INSTANCE_CAST (_tmp18_, BALADOC_API_TYPE_CLASS, BaladocApiClass));
			_tmp20_ = _tmp19_;
			_tmp2_ = _tmp20_;
		} else {
			_tmp2_ = FALSE;
		}
		if (_tmp2_) {
			gchar* _tmp21_ = NULL;
			BaladocApiNode* _tmp22_;
			BaladocApiNode* _tmp23_;
			BaladocApiItem* _tmp24_;
			BaladocApiItem* _tmp25_;
			gchar* _tmp26_;
			GString* _tmp30_;
			_tmp22_ = baladoc_content_symbol_link_get_symbol (sl);
			_tmp23_ = _tmp22_;
			_tmp24_ = baladoc_api_item_get_parent ((BaladocApiItem*) G_TYPE_CHECK_INSTANCE_CAST (_tmp23_, BALADOC_API_TYPE_METHOD, BaladocApiMethod));
			_tmp25_ = _tmp24_;
			_tmp26_ = gtkdoc_get_docbook_link (_tmp25_, self->is_dbus, FALSE);
			_tmp21_ = _tmp26_;
			if (_tmp21_ == NULL) {
				const gchar* _tmp27_;
				const gchar* _tmp28_;
				gchar* _tmp29_;
				_tmp27_ = baladoc_content_symbol_link_get_given_symbol_name (sl);
				_tmp28_ = _tmp27_;
				_tmp29_ = g_strdup (_tmp28_);
				_g_free0 (_tmp21_);
				_tmp21_ = _tmp29_;
			}
			_tmp30_ = self->priv->current_builder;
			g_string_append (_tmp30_, _tmp21_);
			_g_free0 (_tmp21_);
		} else {
			gchar* _tmp31_ = NULL;
			BaladocApiNode* _tmp32_;
			BaladocApiNode* _tmp33_;
			gchar* _tmp34_;
			GString* _tmp38_;
			_tmp32_ = baladoc_content_symbol_link_get_symbol (sl);
			_tmp33_ = _tmp32_;
			_tmp34_ = gtkdoc_get_docbook_link ((BaladocApiItem*) _tmp33_, self->is_dbus, FALSE);
			_tmp31_ = _tmp34_;
			if (_tmp31_ == NULL) {
				const gchar* _tmp35_;
				const gchar* _tmp36_;
				gchar* _tmp37_;
				_tmp35_ = baladoc_content_symbol_link_get_given_symbol_name (sl);
				_tmp36_ = _tmp35_;
				_tmp37_ = g_strdup (_tmp36_);
				_g_free0 (_tmp31_);
				_tmp31_ = _tmp37_;
			}
			_tmp38_ = self->priv->current_builder;
			g_string_append (_tmp38_, _tmp31_);
			_g_free0 (_tmp31_);
		}
	} else {
		GString* _tmp39_;
		const gchar* _tmp40_;
		const gchar* _tmp41_;
		_tmp39_ = self->priv->current_builder;
		_tmp40_ = baladoc_content_symbol_link_get_given_symbol_name (sl);
		_tmp41_ = _tmp40_;
		g_string_append (_tmp39_, _tmp41_);
	}
}

static void
gtkdoc_comment_converter_real_visit_list (BaladocContentContentVisitor* base,
                                          BaladocContentList* list)
{
	GtkdocCommentConverter * self;
	gchar* tag = NULL;
	gchar* _tmp0_;
	BaladocContentListBullet _tmp1_;
	BaladocContentListBullet _tmp2_;
	GString* _tmp17_;
	const gchar* _tmp18_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (list != NULL);
	_tmp0_ = g_strdup ("orderedlist");
	tag = _tmp0_;
	_tmp1_ = baladoc_content_list_get_bullet (list);
	_tmp2_ = _tmp1_;
	switch (_tmp2_) {
		case BALADOC_CONTENT_LIST_BULLET_NONE:
		{
			GString* _tmp3_;
			gchar* _tmp4_;
			_tmp3_ = self->priv->current_builder;
			g_string_append (_tmp3_, "<itemizedlist mark=\"none\">");
			_tmp4_ = g_strdup ("itemizedlist");
			_g_free0 (tag);
			tag = _tmp4_;
			break;
		}
		case BALADOC_CONTENT_LIST_BULLET_UNORDERED:
		{
			GString* _tmp5_;
			gchar* _tmp6_;
			_tmp5_ = self->priv->current_builder;
			g_string_append (_tmp5_, "<itemizedlist>");
			_tmp6_ = g_strdup ("itemizedlist");
			_g_free0 (tag);
			tag = _tmp6_;
			break;
		}
		case BALADOC_CONTENT_LIST_BULLET_ORDERED:
		{
			GString* _tmp7_;
			_tmp7_ = self->priv->current_builder;
			g_string_append (_tmp7_, "<orderedlist>");
			break;
		}
		case BALADOC_CONTENT_LIST_BULLET_ORDERED_NUMBER:
		{
			GString* _tmp8_;
			_tmp8_ = self->priv->current_builder;
			g_string_append (_tmp8_, "<orderedlist numeration=\"arabic\">");
			break;
		}
		case BALADOC_CONTENT_LIST_BULLET_ORDERED_LOWER_CASE_ALPHA:
		{
			GString* _tmp9_;
			_tmp9_ = self->priv->current_builder;
			g_string_append (_tmp9_, "<orderedlist numeration=\"loweralpha\">");
			break;
		}
		case BALADOC_CONTENT_LIST_BULLET_ORDERED_UPPER_CASE_ALPHA:
		{
			GString* _tmp10_;
			_tmp10_ = self->priv->current_builder;
			g_string_append (_tmp10_, "<orderedlist numeration=\"upperalpha\">");
			break;
		}
		case BALADOC_CONTENT_LIST_BULLET_ORDERED_LOWER_CASE_ROMAN:
		{
			GString* _tmp11_;
			_tmp11_ = self->priv->current_builder;
			g_string_append (_tmp11_, "<orderedlist numeration=\"lowerroman\">");
			break;
		}
		case BALADOC_CONTENT_LIST_BULLET_ORDERED_UPPER_CASE_ROMAN:
		{
			GString* _tmp12_;
			_tmp12_ = self->priv->current_builder;
			g_string_append (_tmp12_, "<orderedlist numeration=\"upperroman\">");
			break;
		}
		default:
		{
			BaladocErrorReporter* _tmp13_;
			BaladocContentListBullet _tmp14_;
			BaladocContentListBullet _tmp15_;
			const gchar* _tmp16_;
			_tmp13_ = self->priv->reporter;
			_tmp14_ = baladoc_content_list_get_bullet (list);
			_tmp15_ = _tmp14_;
			_tmp16_ = baladoc_content_list_bullet_to_string (_tmp15_);
			baladoc_error_reporter_simple_warning (_tmp13_, "GtkDoc", "unsupported list type: '%s'", _tmp16_);
			break;
		}
	}
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) list, (BaladocContentContentVisitor*) self);
	_tmp17_ = self->priv->current_builder;
	_tmp18_ = tag;
	g_string_append_printf (_tmp17_, "</%s>", _tmp18_);
	_g_free0 (tag);
}

static void
gtkdoc_comment_converter_real_visit_list_item (BaladocContentContentVisitor* base,
                                               BaladocContentListItem* item)
{
	GtkdocCommentConverter * self;
	GString* _tmp0_;
	GString* _tmp1_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (item != NULL);
	_tmp0_ = self->priv->current_builder;
	g_string_append (_tmp0_, "<listitem>");
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) item, (BaladocContentContentVisitor*) self);
	_tmp1_ = self->priv->current_builder;
	g_string_append (_tmp1_, "</listitem>");
}

static void
gtkdoc_comment_converter_real_visit_paragraph (BaladocContentContentVisitor* base,
                                               BaladocContentParagraph* para)
{
	GtkdocCommentConverter * self;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (para != NULL);
	if (!self->priv->in_brief_comment) {
		GString* _tmp0_;
		_tmp0_ = self->priv->current_builder;
		g_string_append (_tmp0_, "<para>");
	}
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) para, (BaladocContentContentVisitor*) self);
	if (self->priv->in_brief_comment) {
		GString* _tmp1_;
		const gchar* _tmp2_;
		gchar* _tmp3_;
		GString* _tmp4_;
		_tmp1_ = self->priv->current_builder;
		_tmp2_ = _tmp1_->str;
		_tmp3_ = g_strdup (_tmp2_);
		_g_free0 (self->brief_comment);
		self->brief_comment = _tmp3_;
		_tmp4_ = g_string_new ("");
		_g_string_free0 (self->priv->current_builder);
		self->priv->current_builder = _tmp4_;
		self->priv->in_brief_comment = FALSE;
	} else {
		GString* _tmp5_;
		_tmp5_ = self->priv->current_builder;
		g_string_append (_tmp5_, "</para>");
	}
}

static void
gtkdoc_comment_converter_real_visit_warning (BaladocContentContentVisitor* base,
                                             BaladocContentWarning* element)
{
	GtkdocCommentConverter * self;
	GString* _tmp0_;
	GString* _tmp1_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (element != NULL);
	_tmp0_ = self->priv->current_builder;
	g_string_append (_tmp0_, "<warning>");
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) element, (BaladocContentContentVisitor*) self);
	_tmp1_ = self->priv->current_builder;
	g_string_append (_tmp1_, "</warning>");
}

static void
gtkdoc_comment_converter_real_visit_note (BaladocContentContentVisitor* base,
                                          BaladocContentNote* element)
{
	GtkdocCommentConverter * self;
	GString* _tmp0_;
	GString* _tmp1_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (element != NULL);
	_tmp0_ = self->priv->current_builder;
	g_string_append (_tmp0_, "<note>");
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) element, (BaladocContentContentVisitor*) self);
	_tmp1_ = self->priv->current_builder;
	g_string_append (_tmp1_, "</note>");
}

static void
gtkdoc_comment_converter_real_visit_page (BaladocContentContentVisitor* base,
                                          BaladocContentPage* page)
{
	GtkdocCommentConverter * self;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (page != NULL);
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) page, (BaladocContentContentVisitor*) self);
}

static void
gtkdoc_comment_converter_real_visit_run (BaladocContentContentVisitor* base,
                                         BaladocContentRun* run)
{
	GtkdocCommentConverter * self;
	gchar* tag = NULL;
	BaladocContentRunStyle _tmp0_;
	BaladocContentRunStyle _tmp1_;
	const gchar* _tmp10_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (run != NULL);
	tag = NULL;
	_tmp0_ = baladoc_content_run_get_style (run);
	_tmp1_ = _tmp0_;
	switch (_tmp1_) {
		case BALADOC_CONTENT_RUN_STYLE_BOLD:
		{
			GString* _tmp2_;
			gchar* _tmp3_;
			_tmp2_ = self->priv->current_builder;
			g_string_append (_tmp2_, "<emphasis role=\"bold\">");
			_tmp3_ = g_strdup ("emphasis");
			_g_free0 (tag);
			tag = _tmp3_;
			break;
		}
		case BALADOC_CONTENT_RUN_STYLE_ITALIC:
		{
			GString* _tmp4_;
			gchar* _tmp5_;
			_tmp4_ = self->priv->current_builder;
			g_string_append (_tmp4_, "<emphasis>");
			_tmp5_ = g_strdup ("emphasis");
			_g_free0 (tag);
			tag = _tmp5_;
			break;
		}
		case BALADOC_CONTENT_RUN_STYLE_UNDERLINED:
		{
			GString* _tmp6_;
			gchar* _tmp7_;
			_tmp6_ = self->priv->current_builder;
			g_string_append (_tmp6_, "<emphasis role=\"underline\">");
			_tmp7_ = g_strdup ("emphasis");
			_g_free0 (tag);
			tag = _tmp7_;
			break;
		}
		case BALADOC_CONTENT_RUN_STYLE_MONOSPACED:
		{
			GString* _tmp8_;
			gchar* _tmp9_;
			_tmp8_ = self->priv->current_builder;
			g_string_append (_tmp8_, "<code>");
			_tmp9_ = g_strdup ("code");
			_g_free0 (tag);
			tag = _tmp9_;
			break;
		}
		default:
		{
			break;
		}
	}
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) run, (BaladocContentContentVisitor*) self);
	_tmp10_ = tag;
	if (_tmp10_ != NULL) {
		GString* _tmp11_;
		const gchar* _tmp12_;
		_tmp11_ = self->priv->current_builder;
		_tmp12_ = tag;
		g_string_append_printf (_tmp11_, "</%s>", _tmp12_);
	}
	_g_free0 (tag);
}

static void
gtkdoc_comment_converter_real_visit_source_code (BaladocContentContentVisitor* base,
                                                 BaladocContentSourceCode* code)
{
	GtkdocCommentConverter * self;
	GString* _tmp0_;
	GString* _tmp1_;
	const gchar* _tmp2_;
	const gchar* _tmp3_;
	gchar* _tmp4_;
	gchar* _tmp5_;
	GString* _tmp6_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (code != NULL);
	_tmp0_ = self->priv->current_builder;
	g_string_append (_tmp0_, "\n|[\n");
	_tmp1_ = self->priv->current_builder;
	_tmp2_ = baladoc_content_source_code_get_code (code);
	_tmp3_ = _tmp2_;
	_tmp4_ = g_markup_escape_text (_tmp3_, (gssize) -1);
	_tmp5_ = _tmp4_;
	g_string_append (_tmp1_, _tmp5_);
	_g_free0 (_tmp5_);
	_tmp6_ = self->priv->current_builder;
	g_string_append (_tmp6_, "\n]|\n");
}

static void
gtkdoc_comment_converter_real_visit_table (BaladocContentContentVisitor* base,
                                           BaladocContentTable* t)
{
	GtkdocCommentConverter * self;
	GString* _tmp0_;
	GString* _tmp1_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (t != NULL);
	_tmp0_ = self->priv->current_builder;
	g_string_append (_tmp0_, "<table>");
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) t, (BaladocContentContentVisitor*) self);
	_tmp1_ = self->priv->current_builder;
	g_string_append (_tmp1_, "</table>");
}

static void
gtkdoc_comment_converter_real_visit_table_row (BaladocContentContentVisitor* base,
                                               BaladocContentTableRow* row)
{
	GtkdocCommentConverter * self;
	GString* _tmp0_;
	GString* _tmp1_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (row != NULL);
	_tmp0_ = self->priv->current_builder;
	g_string_append (_tmp0_, "<tr>");
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) row, (BaladocContentContentVisitor*) self);
	_tmp1_ = self->priv->current_builder;
	g_string_append (_tmp1_, "</tr>");
}

static void
gtkdoc_comment_converter_real_visit_table_cell (BaladocContentContentVisitor* base,
                                                BaladocContentTableCell* cell)
{
	GtkdocCommentConverter * self;
	GString* _tmp0_;
	GString* _tmp1_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (cell != NULL);
	_tmp0_ = self->priv->current_builder;
	g_string_append (_tmp0_, "<td>");
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) cell, (BaladocContentContentVisitor*) self);
	_tmp1_ = self->priv->current_builder;
	g_string_append (_tmp1_, "</td>");
}

static gchar**
_bala_array_dup1 (gchar** self,
                  gint length)
{
	if (length >= 0) {
		gchar** result;
		gint i;
		result = g_new0 (gchar*, length + 1);
		for (i = 0; i < length; i++) {
			gchar* _tmp0_;
			_tmp0_ = g_strdup (self[i]);
			result[i] = _tmp0_;
		}
		return result;
	}
	return NULL;
}

static void
_bala_array_add1 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}

static void
_bala_array_add2 (gchar** * array,
                  gint* length,
                  gint* size,
                  gchar* value)
{
	if ((*length) == (*size)) {
		*size = (*size) ? (2 * (*size)) : 4;
		*array = g_renew (gchar*, *array, (*size) + 1);
	}
	(*array)[(*length)++] = value;
	(*array)[*length] = NULL;
}

static gchar**
_bala_array_dup2 (gchar** self,
                  gint length)
{
	if (length >= 0) {
		gchar** result;
		gint i;
		result = g_new0 (gchar*, length + 1);
		for (i = 0; i < length; i++) {
			gchar* _tmp0_;
			_tmp0_ = g_strdup (self[i]);
			result[i] = _tmp0_;
		}
		return result;
	}
	return NULL;
}

static void
gtkdoc_comment_converter_real_visit_taglet (BaladocContentContentVisitor* base,
                                            BaladocContentTaglet* t)
{
	GtkdocCommentConverter * self;
	GString* old_builder = NULL;
	GString* _tmp0_;
	GString* _tmp1_;
	GString* _tmp69_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (t != NULL);
	_tmp0_ = self->priv->current_builder;
	self->priv->current_builder = NULL;
	old_builder = _tmp0_;
	_tmp1_ = g_string_new ("");
	_g_string_free0 (self->priv->current_builder);
	self->priv->current_builder = _tmp1_;
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) t, (BaladocContentContentVisitor*) self);
	if (G_TYPE_CHECK_INSTANCE_TYPE (t, BALADOC_TAGLETS_TYPE_PARAM)) {
		gdouble pos = 0.0;
		gchar* param_name = NULL;
		const gchar* _tmp2_;
		const gchar* _tmp3_;
		gchar* _tmp4_;
		BaladocApiNode* _tmp5_;
		GtkdocHeader* header = NULL;
		const gchar* _tmp8_;
		GString* _tmp9_;
		const gchar* _tmp10_;
		GtkdocHeader* _tmp11_;
		BalaList* _tmp12_;
		GtkdocHeader* _tmp13_;
		pos = DBL_MAX;
		_tmp2_ = baladoc_taglets_param_get_parameter_name (G_TYPE_CHECK_INSTANCE_CAST (t, BALADOC_TAGLETS_TYPE_PARAM, BaladocTagletsParam));
		_tmp3_ = _tmp2_;
		_tmp4_ = g_strdup (_tmp3_);
		param_name = _tmp4_;
		_tmp5_ = self->node_reference;
		if (_tmp5_ != NULL) {
			BaladocApiNode* _tmp6_;
			const gchar* _tmp7_;
			_tmp6_ = self->node_reference;
			_tmp7_ = param_name;
			pos = gtkdoc_get_parameter_pos (_tmp6_, _tmp7_);
		}
		_tmp8_ = param_name;
		_tmp9_ = self->priv->current_builder;
		_tmp10_ = _tmp9_->str;
		_tmp11_ = gtkdoc_header_new (_tmp8_, _tmp10_, pos, TRUE);
		header = _tmp11_;
		_tmp12_ = self->parameters;
		_tmp13_ = header;
		bala_collection_add ((BalaCollection*) _tmp12_, _tmp13_);
		_gtkdoc_header_unref0 (header);
		_g_free0 (param_name);
	} else {
		if (G_TYPE_CHECK_INSTANCE_TYPE (t, BALADOC_TAGLETS_TYPE_INHERIT_DOC)) {
			BaladocContentContentElement* _tmp14_;
			BaladocContentContentElement* _tmp15_;
			_tmp14_ = baladoc_content_inline_taglet_produce_content ((BaladocContentInlineTaglet*) G_TYPE_CHECK_INSTANCE_CAST (t, BALADOC_TAGLETS_TYPE_INHERIT_DOC, BaladocTagletsInheritDoc));
			_tmp15_ = _tmp14_;
			baladoc_content_content_element_accept (_tmp15_, (BaladocContentContentVisitor*) self);
			_g_object_unref0 (_tmp15_);
		} else {
			if (G_TYPE_CHECK_INSTANCE_TYPE (t, BALADOC_TAGLETS_TYPE_RETURN)) {
				GString* _tmp16_;
				const gchar* _tmp17_;
				gchar* _tmp18_;
				_tmp16_ = self->priv->current_builder;
				_tmp17_ = _tmp16_->str;
				_tmp18_ = g_strdup (_tmp17_);
				_g_free0 (self->returns);
				self->returns = _tmp18_;
			} else {
				if (G_TYPE_CHECK_INSTANCE_TYPE (t, BALADOC_TAGLETS_TYPE_SINCE)) {
					GtkdocHeader* header = NULL;
					const gchar* _tmp19_;
					const gchar* _tmp20_;
					GtkdocHeader* _tmp21_;
					BalaList* _tmp22_;
					GtkdocHeader* _tmp23_;
					_tmp19_ = baladoc_taglets_since_get_version (G_TYPE_CHECK_INSTANCE_CAST (t, BALADOC_TAGLETS_TYPE_SINCE, BaladocTagletsSince));
					_tmp20_ = _tmp19_;
					_tmp21_ = gtkdoc_header_new ("Since", _tmp20_, DBL_MAX, TRUE);
					header = _tmp21_;
					_tmp22_ = self->versioning;
					_tmp23_ = header;
					bala_collection_add ((BalaCollection*) _tmp22_, _tmp23_);
					_gtkdoc_header_unref0 (header);
				} else {
					if (G_TYPE_CHECK_INSTANCE_TYPE (t, BALADOC_TAGLETS_TYPE_DEPRECATED)) {
						GtkdocHeader* header = NULL;
						GString* _tmp24_;
						const gchar* _tmp25_;
						GtkdocHeader* _tmp26_;
						BalaList* _tmp27_;
						GtkdocHeader* _tmp28_;
						_tmp24_ = self->priv->current_builder;
						_tmp25_ = _tmp24_->str;
						_tmp26_ = gtkdoc_header_new ("Deprecated", _tmp25_, DBL_MAX, TRUE);
						header = _tmp26_;
						_tmp27_ = self->versioning;
						_tmp28_ = header;
						bala_collection_add ((BalaCollection*) _tmp27_, _tmp28_);
						_gtkdoc_header_unref0 (header);
					} else {
						if (G_TYPE_CHECK_INSTANCE_TYPE (t, BALADOC_TAGLETS_TYPE_SEE)) {
							BaladocTagletsSee* see = NULL;
							BaladocTagletsSee* _tmp29_;
							gchar** see_also = NULL;
							gchar** _tmp30_;
							gint _tmp30__length1;
							gchar** _tmp31_;
							gint _tmp31__length1;
							gint see_also_length1;
							gint _see_also_size_;
							BaladocTagletsSee* _tmp32_;
							BaladocApiNode* _tmp33_;
							BaladocApiNode* _tmp34_;
							gchar** _tmp49_;
							gint _tmp49__length1;
							gchar** _tmp50_;
							gint _tmp50__length1;
							_tmp29_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (t, BALADOC_TAGLETS_TYPE_SEE, BaladocTagletsSee));
							see = _tmp29_;
							_tmp30_ = self->see_also;
							_tmp30__length1 = self->see_also_length1;
							_tmp31_ = (_tmp30_ != NULL) ? _bala_array_dup1 (_tmp30_, _tmp30__length1) : ((gpointer) _tmp30_);
							_tmp31__length1 = _tmp30__length1;
							see_also = _tmp31_;
							see_also_length1 = _tmp31__length1;
							_see_also_size_ = see_also_length1;
							_tmp32_ = see;
							_tmp33_ = baladoc_taglets_see_get_symbol (_tmp32_);
							_tmp34_ = _tmp33_;
							if (_tmp34_ != NULL) {
								gchar* _tmp35_ = NULL;
								BaladocTagletsSee* _tmp36_;
								BaladocApiNode* _tmp37_;
								BaladocApiNode* _tmp38_;
								gchar* _tmp39_;
								gchar* _tmp44_;
								_tmp36_ = see;
								_tmp37_ = baladoc_taglets_see_get_symbol (_tmp36_);
								_tmp38_ = _tmp37_;
								_tmp39_ = gtkdoc_get_docbook_link ((BaladocApiItem*) _tmp38_, self->is_dbus, FALSE);
								_tmp35_ = _tmp39_;
								if (_tmp35_ == NULL) {
									BaladocTagletsSee* _tmp40_;
									const gchar* _tmp41_;
									const gchar* _tmp42_;
									gchar* _tmp43_;
									_tmp40_ = see;
									_tmp41_ = baladoc_taglets_see_get_symbol_name (_tmp40_);
									_tmp42_ = _tmp41_;
									_tmp43_ = g_strdup (_tmp42_);
									_g_free0 (_tmp35_);
									_tmp35_ = _tmp43_;
								}
								_tmp44_ = _tmp35_;
								_tmp35_ = NULL;
								_bala_array_add1 (&see_also, &see_also_length1, &_see_also_size_, _tmp44_);
								_g_free0 (_tmp35_);
							} else {
								BaladocTagletsSee* _tmp45_;
								const gchar* _tmp46_;
								const gchar* _tmp47_;
								gchar* _tmp48_;
								_tmp45_ = see;
								_tmp46_ = baladoc_taglets_see_get_symbol_name (_tmp45_);
								_tmp47_ = _tmp46_;
								_tmp48_ = g_strdup (_tmp47_);
								_bala_array_add2 (&see_also, &see_also_length1, &_see_also_size_, _tmp48_);
							}
							_tmp49_ = see_also;
							_tmp49__length1 = see_also_length1;
							_tmp50_ = (_tmp49_ != NULL) ? _bala_array_dup2 (_tmp49_, _tmp49__length1) : ((gpointer) _tmp49_);
							_tmp50__length1 = _tmp49__length1;
							self->see_also = (_bala_array_free (self->see_also, self->see_also_length1, (GDestroyNotify) g_free), NULL);
							self->see_also = _tmp50_;
							self->see_also_length1 = _tmp50__length1;
							see_also = (_bala_array_free (see_also, see_also_length1, (GDestroyNotify) g_free), NULL);
							_g_object_unref0 (see);
						} else {
							if (G_TYPE_CHECK_INSTANCE_TYPE (t, BALADOC_TAGLETS_TYPE_LINK)) {
								BaladocContentContentElement* _tmp51_;
								BaladocContentContentElement* _tmp52_;
								_tmp51_ = baladoc_content_inline_taglet_produce_content ((BaladocContentInlineTaglet*) G_TYPE_CHECK_INSTANCE_CAST (t, BALADOC_TAGLETS_TYPE_LINK, BaladocTagletsLink));
								_tmp52_ = _tmp51_;
								baladoc_content_content_element_accept (_tmp52_, (BaladocContentContentVisitor*) self);
								_g_object_unref0 (_tmp52_);
							} else {
								if (G_TYPE_CHECK_INSTANCE_TYPE (t, BALADOC_TAGLETS_TYPE_THROWS)) {
									BaladocTagletsThrows* taglet = NULL;
									BaladocTagletsThrows* _tmp53_;
									gchar* _tmp54_ = NULL;
									BaladocTagletsThrows* _tmp55_;
									BaladocApiNode* _tmp56_;
									BaladocApiNode* _tmp57_;
									gchar* _tmp58_;
									gchar* link = NULL;
									gchar* _tmp63_;
									GString* _tmp64_;
									const gchar* _tmp65_;
									GString* _tmp66_;
									const gchar* _tmp67_;
									_tmp53_ = _g_object_ref0 (G_TYPE_CHECK_INSTANCE_CAST (t, BALADOC_TAGLETS_TYPE_THROWS, BaladocTagletsThrows));
									taglet = _tmp53_;
									_tmp55_ = taglet;
									_tmp56_ = baladoc_taglets_throws_get_error_domain (_tmp55_);
									_tmp57_ = _tmp56_;
									_tmp58_ = gtkdoc_get_docbook_link ((BaladocApiItem*) _tmp57_, FALSE, FALSE);
									_tmp54_ = _tmp58_;
									if (_tmp54_ == NULL) {
										BaladocTagletsThrows* _tmp59_;
										const gchar* _tmp60_;
										const gchar* _tmp61_;
										gchar* _tmp62_;
										_tmp59_ = taglet;
										_tmp60_ = baladoc_taglets_throws_get_error_domain_name (_tmp59_);
										_tmp61_ = _tmp60_;
										_tmp62_ = g_strdup (_tmp61_);
										_g_free0 (_tmp54_);
										_tmp54_ = _tmp62_;
									}
									_tmp63_ = _tmp54_;
									_tmp54_ = NULL;
									link = _tmp63_;
									_tmp64_ = old_builder;
									_tmp65_ = link;
									_tmp66_ = self->priv->current_builder;
									_tmp67_ = _tmp66_->str;
									g_string_append_printf (_tmp64_, "\n<para>%s will be returned in @error %s</para>", _tmp65_, _tmp67_);
									_g_free0 (link);
									_g_free0 (_tmp54_);
									_g_object_unref0 (taglet);
								} else {
									BaladocErrorReporter* _tmp68_;
									_tmp68_ = self->priv->reporter;
									baladoc_error_reporter_simple_warning (_tmp68_, "GtkDoc", "Taglet not supported");
								}
							}
						}
					}
				}
			}
		}
	}
	_tmp69_ = old_builder;
	old_builder = NULL;
	_g_string_free0 (self->priv->current_builder);
	self->priv->current_builder = _tmp69_;
	_g_string_free0 (old_builder);
}

static void
gtkdoc_comment_converter_real_visit_text (BaladocContentContentVisitor* base,
                                          BaladocContentText* t)
{
	GtkdocCommentConverter * self;
	GString* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	self = (GtkdocCommentConverter*) base;
	g_return_if_fail (t != NULL);
	_tmp0_ = self->priv->current_builder;
	_tmp1_ = baladoc_content_text_get_content (t);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_markup_escape_text (_tmp2_, (gssize) -1);
	_tmp4_ = _tmp3_;
	g_string_append (_tmp0_, _tmp4_);
	_g_free0 (_tmp4_);
	baladoc_content_content_element_accept_children ((BaladocContentContentElement*) t, (BaladocContentContentVisitor*) self);
}

static void
gtkdoc_comment_converter_class_init (GtkdocCommentConverterClass * klass,
                                     gpointer klass_data)
{
	gtkdoc_comment_converter_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &GtkdocCommentConverter_private_offset);
	((BaladocContentContentVisitorClass *) klass)->visit_comment = (void (*) (BaladocContentContentVisitor*, BaladocContentComment*)) gtkdoc_comment_converter_real_visit_comment;
	((BaladocContentContentVisitorClass *) klass)->visit_embedded = (void (*) (BaladocContentContentVisitor*, BaladocContentEmbedded*)) gtkdoc_comment_converter_real_visit_embedded;
	((BaladocContentContentVisitorClass *) klass)->visit_headline = (void (*) (BaladocContentContentVisitor*, BaladocContentHeadline*)) gtkdoc_comment_converter_real_visit_headline;
	((BaladocContentContentVisitorClass *) klass)->visit_wiki_link = (void (*) (BaladocContentContentVisitor*, BaladocContentWikiLink*)) gtkdoc_comment_converter_real_visit_wiki_link;
	((BaladocContentContentVisitorClass *) klass)->visit_link = (void (*) (BaladocContentContentVisitor*, BaladocContentLink*)) gtkdoc_comment_converter_real_visit_link;
	((BaladocContentContentVisitorClass *) klass)->visit_symbol_link = (void (*) (BaladocContentContentVisitor*, BaladocContentSymbolLink*)) gtkdoc_comment_converter_real_visit_symbol_link;
	((BaladocContentContentVisitorClass *) klass)->visit_list = (void (*) (BaladocContentContentVisitor*, BaladocContentList*)) gtkdoc_comment_converter_real_visit_list;
	((BaladocContentContentVisitorClass *) klass)->visit_list_item = (void (*) (BaladocContentContentVisitor*, BaladocContentListItem*)) gtkdoc_comment_converter_real_visit_list_item;
	((BaladocContentContentVisitorClass *) klass)->visit_paragraph = (void (*) (BaladocContentContentVisitor*, BaladocContentParagraph*)) gtkdoc_comment_converter_real_visit_paragraph;
	((BaladocContentContentVisitorClass *) klass)->visit_warning = (void (*) (BaladocContentContentVisitor*, BaladocContentWarning*)) gtkdoc_comment_converter_real_visit_warning;
	((BaladocContentContentVisitorClass *) klass)->visit_note = (void (*) (BaladocContentContentVisitor*, BaladocContentNote*)) gtkdoc_comment_converter_real_visit_note;
	((BaladocContentContentVisitorClass *) klass)->visit_page = (void (*) (BaladocContentContentVisitor*, BaladocContentPage*)) gtkdoc_comment_converter_real_visit_page;
	((BaladocContentContentVisitorClass *) klass)->visit_run = (void (*) (BaladocContentContentVisitor*, BaladocContentRun*)) gtkdoc_comment_converter_real_visit_run;
	((BaladocContentContentVisitorClass *) klass)->visit_source_code = (void (*) (BaladocContentContentVisitor*, BaladocContentSourceCode*)) gtkdoc_comment_converter_real_visit_source_code;
	((BaladocContentContentVisitorClass *) klass)->visit_table = (void (*) (BaladocContentContentVisitor*, BaladocContentTable*)) gtkdoc_comment_converter_real_visit_table;
	((BaladocContentContentVisitorClass *) klass)->visit_table_row = (void (*) (BaladocContentContentVisitor*, BaladocContentTableRow*)) gtkdoc_comment_converter_real_visit_table_row;
	((BaladocContentContentVisitorClass *) klass)->visit_table_cell = (void (*) (BaladocContentContentVisitor*, BaladocContentTableCell*)) gtkdoc_comment_converter_real_visit_table_cell;
	((BaladocContentContentVisitorClass *) klass)->visit_taglet = (void (*) (BaladocContentContentVisitor*, BaladocContentTaglet*)) gtkdoc_comment_converter_real_visit_taglet;
	((BaladocContentContentVisitorClass *) klass)->visit_text = (void (*) (BaladocContentContentVisitor*, BaladocContentText*)) gtkdoc_comment_converter_real_visit_text;
	G_OBJECT_CLASS (klass)->finalize = gtkdoc_comment_converter_finalize;
}

static void
gtkdoc_comment_converter_instance_init (GtkdocCommentConverter * self,
                                        gpointer klass)
{
	GEqualFunc _tmp0_;
	BalaArrayList* _tmp1_;
	GEqualFunc _tmp2_;
	BalaArrayList* _tmp3_;
	gchar** _tmp4_;
	GString* _tmp5_;
	self->priv = gtkdoc_comment_converter_get_instance_private (self);
	_tmp0_ = g_direct_equal;
	_tmp1_ = bala_array_list_new (GTKDOC_TYPE_HEADER, (GBoxedCopyFunc) gtkdoc_header_ref, (GDestroyNotify) gtkdoc_header_unref, _tmp0_);
	self->parameters = (BalaList*) _tmp1_;
	_tmp2_ = g_direct_equal;
	_tmp3_ = bala_array_list_new (GTKDOC_TYPE_HEADER, (GBoxedCopyFunc) gtkdoc_header_ref, (GDestroyNotify) gtkdoc_header_unref, _tmp2_);
	self->versioning = (BalaList*) _tmp3_;
	_tmp4_ = g_new0 (gchar*, 0 + 1);
	self->see_also = _tmp4_;
	self->see_also_length1 = 0;
	_tmp5_ = g_string_new ("");
	self->priv->current_builder = _tmp5_;
	self->priv->in_brief_comment = TRUE;
}

static void
gtkdoc_comment_converter_finalize (GObject * obj)
{
	GtkdocCommentConverter * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, GTKDOC_TYPE_COMMENT_CONVERTER, GtkdocCommentConverter);
	_g_object_unref0 (self->node_reference);
	_g_free0 (self->brief_comment);
	_g_free0 (self->long_comment);
	_g_free0 (self->returns);
	_bala_iterable_unref0 (self->parameters);
	_bala_iterable_unref0 (self->versioning);
	self->see_also = (_bala_array_free (self->see_also, self->see_also_length1, (GDestroyNotify) g_free), NULL);
	_g_string_free0 (self->priv->current_builder);
	_g_object_unref0 (self->priv->reporter);
	G_OBJECT_CLASS (gtkdoc_comment_converter_parent_class)->finalize (obj);
}

static GType
gtkdoc_comment_converter_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (GtkdocCommentConverterClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) gtkdoc_comment_converter_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (GtkdocCommentConverter), 0, (GInstanceInitFunc) gtkdoc_comment_converter_instance_init, NULL };
	GType gtkdoc_comment_converter_type_id;
	gtkdoc_comment_converter_type_id = g_type_register_static (BALADOC_CONTENT_TYPE_CONTENT_VISITOR, "GtkdocCommentConverter", &g_define_type_info, 0);
	GtkdocCommentConverter_private_offset = g_type_add_instance_private (gtkdoc_comment_converter_type_id, sizeof (GtkdocCommentConverterPrivate));
	return gtkdoc_comment_converter_type_id;
}

GType
gtkdoc_comment_converter_get_type (void)
{
	static volatile gsize gtkdoc_comment_converter_type_id__volatile = 0;
	if (g_once_init_enter (&gtkdoc_comment_converter_type_id__volatile)) {
		GType gtkdoc_comment_converter_type_id;
		gtkdoc_comment_converter_type_id = gtkdoc_comment_converter_get_type_once ();
		g_once_init_leave (&gtkdoc_comment_converter_type_id__volatile, gtkdoc_comment_converter_type_id);
	}
	return gtkdoc_comment_converter_type_id__volatile;
}

static void
_bala_array_destroy (gpointer array,
                     gint array_length,
                     GDestroyNotify destroy_func)
{
	if ((array != NULL) && (destroy_func != NULL)) {
		gint i;
		for (i = 0; i < array_length; i = i + 1) {
			if (((gpointer*) array)[i] != NULL) {
				destroy_func (((gpointer*) array)[i]);
			}
		}
	}
}

static void
_bala_array_free (gpointer array,
                  gint array_length,
                  GDestroyNotify destroy_func)
{
	_bala_array_destroy (array, array_length, destroy_func);
	g_free (array);
}

