/* enumvalue.c generated by balac, the Bala compiler
 * generated from enumvalue.bala, do not modify */

/* enumvalue.bala
 *
 * Copyright (C) 2008-2011  Florian Brosch
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Florian Brosch <flo.brosch@gmail.com>
 */

#include "baladoc.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>
#include <bala.h>
#include <balacodegen.h>

enum  {
	BALADOC_API_ENUM_VALUE_0_PROPERTY,
	BALADOC_API_ENUM_VALUE_DEFAULT_VALUE_PROPERTY,
	BALADOC_API_ENUM_VALUE_HAS_DEFAULT_VALUE_PROPERTY,
	BALADOC_API_ENUM_VALUE_NODE_TYPE_PROPERTY,
	BALADOC_API_ENUM_VALUE_NUM_PROPERTIES
};
static GParamSpec* baladoc_api_enum_value_properties[BALADOC_API_ENUM_VALUE_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _baladoc_api_signature_builder_unref0(var) ((var == NULL) ? NULL : (var = (baladoc_api_signature_builder_unref (var), NULL)))

struct _BaladocApiEnumValuePrivate {
	gchar* cname;
	BaladocContentRun* _default_value;
};

static gint BaladocApiEnumValue_private_offset;
static gpointer baladoc_api_enum_value_parent_class = NULL;

static void baladoc_api_enum_value_real_accept (BaladocApiNode* base,
                                         BaladocApiVisitor* visitor);
static BaladocContentInline* baladoc_api_enum_value_real_build_signature (BaladocApiItem* base);
static void baladoc_api_enum_value_finalize (GObject * obj);
static GType baladoc_api_enum_value_get_type_once (void);
static void _bala_baladoc_api_enum_value_get_property (GObject * object,
                                                guint property_id,
                                                GValue * value,
                                                GParamSpec * pspec);
static void _bala_baladoc_api_enum_value_set_property (GObject * object,
                                                guint property_id,
                                                const GValue * value,
                                                GParamSpec * pspec);

static inline gpointer
baladoc_api_enum_value_get_instance_private (BaladocApiEnumValue* self)
{
	return G_STRUCT_MEMBER_P (self, BaladocApiEnumValue_private_offset);
}

BaladocContentRun*
baladoc_api_enum_value_get_default_value (BaladocApiEnumValue* self)
{
	BaladocContentRun* result;
	BaladocContentRun* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_default_value;
	result = _tmp0_;
	return result;
}

static gpointer
_g_object_ref0 (gpointer self)
{
	return self ? g_object_ref (self) : NULL;
}

void
baladoc_api_enum_value_set_default_value (BaladocApiEnumValue* self,
                                          BaladocContentRun* value)
{
	BaladocContentRun* old_value;
	g_return_if_fail (self != NULL);
	old_value = baladoc_api_enum_value_get_default_value (self);
	if (old_value != value) {
		BaladocContentRun* _tmp0_;
		_tmp0_ = _g_object_ref0 (value);
		_g_object_unref0 (self->priv->_default_value);
		self->priv->_default_value = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, baladoc_api_enum_value_properties[BALADOC_API_ENUM_VALUE_DEFAULT_VALUE_PROPERTY]);
	}
}

gboolean
baladoc_api_enum_value_get_has_default_value (BaladocApiEnumValue* self)
{
	gboolean result;
	BaladocContentRun* _tmp0_;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_default_value;
	result = _tmp0_ != NULL;
	return result;
}

BaladocApiEnumValue*
baladoc_api_enum_value_construct (GType object_type,
                                  BaladocApiEnum* parent,
                                  BaladocApiSourceFile* file,
                                  const gchar* name,
                                  BaladocApiSourceComment* comment,
                                  BalaEnumValue* data)
{
	BaladocApiEnumValue * self = NULL;
	BalaSymbolAccessibility _tmp0_;
	BalaSymbolAccessibility _tmp1_;
	gchar* _tmp2_;
	g_return_val_if_fail (parent != NULL, NULL);
	g_return_val_if_fail (file != NULL, NULL);
	g_return_val_if_fail (name != NULL, NULL);
	g_return_val_if_fail (data != NULL, NULL);
	_tmp0_ = baladoc_api_symbol_get_accessibility ((BaladocApiSymbol*) parent);
	_tmp1_ = _tmp0_;
	self = (BaladocApiEnumValue*) baladoc_api_symbol_construct (object_type, (BaladocApiNode*) parent, file, name, _tmp1_, comment, (BalaSymbol*) data);
	_tmp2_ = bala_get_ccode_name ((BalaCodeNode*) data);
	_g_free0 (self->priv->cname);
	self->priv->cname = _tmp2_;
	return self;
}

BaladocApiEnumValue*
baladoc_api_enum_value_new (BaladocApiEnum* parent,
                            BaladocApiSourceFile* file,
                            const gchar* name,
                            BaladocApiSourceComment* comment,
                            BalaEnumValue* data)
{
	return baladoc_api_enum_value_construct (BALADOC_API_TYPE_ENUM_VALUE, parent, file, name, comment, data);
}

/**
 * Returns the name of this enum value as it is used in C.
 */
gchar*
baladoc_api_enum_value_get_cname (BaladocApiEnumValue* self)
{
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* result = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->cname;
	_tmp1_ = g_strdup (_tmp0_);
	result = _tmp1_;
	return result;
}

static BaladocApiNodeType
baladoc_api_enum_value_real_get_node_type (BaladocApiNode* base)
{
	BaladocApiNodeType result;
	BaladocApiEnumValue* self;
	self = (BaladocApiEnumValue*) base;
	result = BALADOC_API_NODE_TYPE_ENUM_VALUE;
	return result;
}

/**
 * {@inheritDoc}
 */
static void
baladoc_api_enum_value_real_accept (BaladocApiNode* base,
                                    BaladocApiVisitor* visitor)
{
	BaladocApiEnumValue * self;
	self = (BaladocApiEnumValue*) base;
	g_return_if_fail (visitor != NULL);
	baladoc_api_visitor_visit_enum_value (visitor, self);
}

/**
 * {@inheritDoc}
 */
static gpointer
_baladoc_api_signature_builder_ref0 (gpointer self)
{
	return self ? baladoc_api_signature_builder_ref (self) : NULL;
}

static BaladocContentInline*
baladoc_api_enum_value_real_build_signature (BaladocApiItem* base)
{
	BaladocApiEnumValue * self;
	BaladocApiSignatureBuilder* builder = NULL;
	BaladocApiSignatureBuilder* _tmp0_;
	BaladocApiSignatureBuilder* _tmp1_;
	BaladocApiSignatureBuilder* _tmp2_;
	BaladocApiSignatureBuilder* _tmp3_;
	BaladocApiSignatureBuilder* _tmp4_;
	gboolean _tmp5_;
	gboolean _tmp6_;
	BaladocApiSignatureBuilder* _tmp10_;
	BaladocContentRun* _tmp11_;
	BaladocContentInline* result = NULL;
	self = (BaladocApiEnumValue*) base;
	_tmp0_ = baladoc_api_signature_builder_new ();
	_tmp1_ = _tmp0_;
	_tmp2_ = baladoc_api_signature_builder_append_symbol (_tmp1_, (BaladocApiNode*) self, TRUE);
	_tmp3_ = _baladoc_api_signature_builder_ref0 (_tmp2_);
	_tmp4_ = _tmp3_;
	_baladoc_api_signature_builder_unref0 (_tmp1_);
	builder = _tmp4_;
	_tmp5_ = baladoc_api_enum_value_get_has_default_value (self);
	_tmp6_ = _tmp5_;
	if (_tmp6_) {
		BaladocApiSignatureBuilder* _tmp7_;
		BaladocApiSignatureBuilder* _tmp8_;
		BaladocContentRun* _tmp9_;
		_tmp7_ = builder;
		baladoc_api_signature_builder_append (_tmp7_, "=", TRUE);
		_tmp8_ = builder;
		_tmp9_ = self->priv->_default_value;
		baladoc_api_signature_builder_append_content (_tmp8_, (BaladocContentInline*) _tmp9_, TRUE);
	}
	_tmp10_ = builder;
	_tmp11_ = baladoc_api_signature_builder_get (_tmp10_);
	result = (BaladocContentInline*) _tmp11_;
	_baladoc_api_signature_builder_unref0 (builder);
	return result;
}

static void
baladoc_api_enum_value_class_init (BaladocApiEnumValueClass * klass,
                                   gpointer klass_data)
{
	baladoc_api_enum_value_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &BaladocApiEnumValue_private_offset);
	((BaladocApiNodeClass *) klass)->accept = (void (*) (BaladocApiNode*, BaladocApiVisitor*)) baladoc_api_enum_value_real_accept;
	((BaladocApiItemClass *) klass)->build_signature = (BaladocContentInline* (*) (BaladocApiItem*)) baladoc_api_enum_value_real_build_signature;
	BALADOC_API_NODE_CLASS (klass)->get_node_type = baladoc_api_enum_value_real_get_node_type;
	G_OBJECT_CLASS (klass)->get_property = _bala_baladoc_api_enum_value_get_property;
	G_OBJECT_CLASS (klass)->set_property = _bala_baladoc_api_enum_value_set_property;
	G_OBJECT_CLASS (klass)->finalize = baladoc_api_enum_value_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), BALADOC_API_ENUM_VALUE_DEFAULT_VALUE_PROPERTY, baladoc_api_enum_value_properties[BALADOC_API_ENUM_VALUE_DEFAULT_VALUE_PROPERTY] = g_param_spec_object ("default-value", "default-value", "default-value", BALADOC_CONTENT_TYPE_RUN, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
	/**
	 * Specifies whether the parameter has a default value
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), BALADOC_API_ENUM_VALUE_HAS_DEFAULT_VALUE_PROPERTY, baladoc_api_enum_value_properties[BALADOC_API_ENUM_VALUE_HAS_DEFAULT_VALUE_PROPERTY] = g_param_spec_boolean ("has-default-value", "has-default-value", "has-default-value", FALSE, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
	/**
	 * {@inheritDoc}
	 */
	g_object_class_install_property (G_OBJECT_CLASS (klass), BALADOC_API_ENUM_VALUE_NODE_TYPE_PROPERTY, baladoc_api_enum_value_properties[BALADOC_API_ENUM_VALUE_NODE_TYPE_PROPERTY] = g_param_spec_enum ("node-type", "node-type", "node-type", BALADOC_API_TYPE_NODE_TYPE, 0, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE));
}

static void
baladoc_api_enum_value_instance_init (BaladocApiEnumValue * self,
                                      gpointer klass)
{
	self->priv = baladoc_api_enum_value_get_instance_private (self);
}

static void
baladoc_api_enum_value_finalize (GObject * obj)
{
	BaladocApiEnumValue * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BALADOC_API_TYPE_ENUM_VALUE, BaladocApiEnumValue);
	_g_free0 (self->priv->cname);
	_g_object_unref0 (self->priv->_default_value);
	G_OBJECT_CLASS (baladoc_api_enum_value_parent_class)->finalize (obj);
}

/**
 * Represents an enum member.
 */
static GType
baladoc_api_enum_value_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (BaladocApiEnumValueClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) baladoc_api_enum_value_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BaladocApiEnumValue), 0, (GInstanceInitFunc) baladoc_api_enum_value_instance_init, NULL };
	GType baladoc_api_enum_value_type_id;
	baladoc_api_enum_value_type_id = g_type_register_static (BALADOC_API_TYPE_SYMBOL, "BaladocApiEnumValue", &g_define_type_info, 0);
	BaladocApiEnumValue_private_offset = g_type_add_instance_private (baladoc_api_enum_value_type_id, sizeof (BaladocApiEnumValuePrivate));
	return baladoc_api_enum_value_type_id;
}

GType
baladoc_api_enum_value_get_type (void)
{
	static volatile gsize baladoc_api_enum_value_type_id__volatile = 0;
	if (g_once_init_enter (&baladoc_api_enum_value_type_id__volatile)) {
		GType baladoc_api_enum_value_type_id;
		baladoc_api_enum_value_type_id = baladoc_api_enum_value_get_type_once ();
		g_once_init_leave (&baladoc_api_enum_value_type_id__volatile, baladoc_api_enum_value_type_id);
	}
	return baladoc_api_enum_value_type_id__volatile;
}

static void
_bala_baladoc_api_enum_value_get_property (GObject * object,
                                           guint property_id,
                                           GValue * value,
                                           GParamSpec * pspec)
{
	BaladocApiEnumValue * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, BALADOC_API_TYPE_ENUM_VALUE, BaladocApiEnumValue);
	switch (property_id) {
		case BALADOC_API_ENUM_VALUE_DEFAULT_VALUE_PROPERTY:
		g_value_set_object (value, baladoc_api_enum_value_get_default_value (self));
		break;
		case BALADOC_API_ENUM_VALUE_HAS_DEFAULT_VALUE_PROPERTY:
		g_value_set_boolean (value, baladoc_api_enum_value_get_has_default_value (self));
		break;
		case BALADOC_API_ENUM_VALUE_NODE_TYPE_PROPERTY:
		g_value_set_enum (value, baladoc_api_node_get_node_type ((BaladocApiNode*) self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_bala_baladoc_api_enum_value_set_property (GObject * object,
                                           guint property_id,
                                           const GValue * value,
                                           GParamSpec * pspec)
{
	BaladocApiEnumValue * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, BALADOC_API_TYPE_ENUM_VALUE, BaladocApiEnumValue);
	switch (property_id) {
		case BALADOC_API_ENUM_VALUE_DEFAULT_VALUE_PROPERTY:
		baladoc_api_enum_value_set_default_value (self, g_value_get_object (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

