/* balaccodebinaryexpression.c generated by balac, the Bala compiler
 * generated from balaccodebinaryexpression.bala, do not modify */

/* balaccodebinaryexpression.bala
 *
 * Copyright (C) 2006-2008  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 */

#include "balaccode.h"
#include <glib.h>

#define _bala_ccode_node_unref0(var) ((var == NULL) ? NULL : (var = (bala_ccode_node_unref (var), NULL)))

struct _BalaCCodeBinaryExpressionPrivate {
	BalaCCodeBinaryOperator _operator;
	BalaCCodeExpression* _left;
	BalaCCodeExpression* _right;
};

static gint BalaCCodeBinaryExpression_private_offset;
static gpointer bala_ccode_binary_expression_parent_class = NULL;

static void bala_ccode_binary_expression_real_write (BalaCCodeNode* base,
                                              BalaCCodeWriter* writer);
static void bala_ccode_binary_expression_real_write_inner (BalaCCodeExpression* base,
                                                    BalaCCodeWriter* writer);
static void bala_ccode_binary_expression_finalize (BalaCCodeNode * obj);
static GType bala_ccode_binary_expression_get_type_once (void);

static inline gpointer
bala_ccode_binary_expression_get_instance_private (BalaCCodeBinaryExpression* self)
{
	return G_STRUCT_MEMBER_P (self, BalaCCodeBinaryExpression_private_offset);
}

BalaCCodeBinaryOperator
bala_ccode_binary_expression_get_operator (BalaCCodeBinaryExpression* self)
{
	BalaCCodeBinaryOperator result;
	BalaCCodeBinaryOperator _tmp0_;
	g_return_val_if_fail (self != NULL, 0);
	_tmp0_ = self->priv->_operator;
	result = _tmp0_;
	return result;
}

void
bala_ccode_binary_expression_set_operator (BalaCCodeBinaryExpression* self,
                                           BalaCCodeBinaryOperator value)
{
	g_return_if_fail (self != NULL);
	self->priv->_operator = value;
}

BalaCCodeExpression*
bala_ccode_binary_expression_get_left (BalaCCodeBinaryExpression* self)
{
	BalaCCodeExpression* result;
	BalaCCodeExpression* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_left;
	result = _tmp0_;
	return result;
}

static gpointer
_bala_ccode_node_ref0 (gpointer self)
{
	return self ? bala_ccode_node_ref (self) : NULL;
}

void
bala_ccode_binary_expression_set_left (BalaCCodeBinaryExpression* self,
                                       BalaCCodeExpression* value)
{
	BalaCCodeExpression* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _bala_ccode_node_ref0 (value);
	_bala_ccode_node_unref0 (self->priv->_left);
	self->priv->_left = _tmp0_;
}

BalaCCodeExpression*
bala_ccode_binary_expression_get_right (BalaCCodeBinaryExpression* self)
{
	BalaCCodeExpression* result;
	BalaCCodeExpression* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_right;
	result = _tmp0_;
	return result;
}

void
bala_ccode_binary_expression_set_right (BalaCCodeBinaryExpression* self,
                                        BalaCCodeExpression* value)
{
	BalaCCodeExpression* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _bala_ccode_node_ref0 (value);
	_bala_ccode_node_unref0 (self->priv->_right);
	self->priv->_right = _tmp0_;
}

BalaCCodeBinaryExpression*
bala_ccode_binary_expression_construct (GType object_type,
                                        BalaCCodeBinaryOperator op,
                                        BalaCCodeExpression* l,
                                        BalaCCodeExpression* r)
{
	BalaCCodeBinaryExpression* self = NULL;
	g_return_val_if_fail (l != NULL, NULL);
	g_return_val_if_fail (r != NULL, NULL);
	self = (BalaCCodeBinaryExpression*) bala_ccode_expression_construct (object_type);
	bala_ccode_binary_expression_set_operator (self, op);
	bala_ccode_binary_expression_set_left (self, l);
	bala_ccode_binary_expression_set_right (self, r);
	return self;
}

BalaCCodeBinaryExpression*
bala_ccode_binary_expression_new (BalaCCodeBinaryOperator op,
                                  BalaCCodeExpression* l,
                                  BalaCCodeExpression* r)
{
	return bala_ccode_binary_expression_construct (BALA_TYPE_CCODE_BINARY_EXPRESSION, op, l, r);
}

static void
bala_ccode_binary_expression_real_write (BalaCCodeNode* base,
                                         BalaCCodeWriter* writer)
{
	BalaCCodeBinaryExpression * self;
	BalaCCodeExpression* _tmp0_;
	BalaCCodeBinaryOperator _tmp1_;
	BalaCCodeExpression* _tmp2_;
	self = (BalaCCodeBinaryExpression*) base;
	g_return_if_fail (writer != NULL);
	_tmp0_ = self->priv->_left;
	bala_ccode_expression_write_inner (_tmp0_, writer);
	_tmp1_ = self->priv->_operator;
	switch (_tmp1_) {
		case BALA_CCODE_BINARY_OPERATOR_PLUS:
		{
			bala_ccode_writer_write_string (writer, " + ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_MINUS:
		{
			bala_ccode_writer_write_string (writer, " - ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_MUL:
		{
			bala_ccode_writer_write_string (writer, " * ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_DIV:
		{
			bala_ccode_writer_write_string (writer, " / ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_MOD:
		{
			bala_ccode_writer_write_string (writer, " % ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_SHIFT_LEFT:
		{
			bala_ccode_writer_write_string (writer, " << ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_SHIFT_RIGHT:
		{
			bala_ccode_writer_write_string (writer, " >> ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_LESS_THAN:
		{
			bala_ccode_writer_write_string (writer, " < ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_GREATER_THAN:
		{
			bala_ccode_writer_write_string (writer, " > ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_LESS_THAN_OR_EQUAL:
		{
			bala_ccode_writer_write_string (writer, " <= ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_GREATER_THAN_OR_EQUAL:
		{
			bala_ccode_writer_write_string (writer, " >= ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_EQUALITY:
		{
			bala_ccode_writer_write_string (writer, " == ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_INEQUALITY:
		{
			bala_ccode_writer_write_string (writer, " != ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_BITWISE_AND:
		{
			bala_ccode_writer_write_string (writer, " & ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_BITWISE_OR:
		{
			bala_ccode_writer_write_string (writer, " | ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_BITWISE_XOR:
		{
			bala_ccode_writer_write_string (writer, " ^ ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_AND:
		{
			bala_ccode_writer_write_string (writer, " && ");
			break;
		}
		case BALA_CCODE_BINARY_OPERATOR_OR:
		{
			bala_ccode_writer_write_string (writer, " || ");
			break;
		}
		default:
		{
			g_assert_not_reached ();
		}
	}
	_tmp2_ = self->priv->_right;
	bala_ccode_expression_write_inner (_tmp2_, writer);
}

static void
bala_ccode_binary_expression_real_write_inner (BalaCCodeExpression* base,
                                               BalaCCodeWriter* writer)
{
	BalaCCodeBinaryExpression * self;
	self = (BalaCCodeBinaryExpression*) base;
	g_return_if_fail (writer != NULL);
	bala_ccode_writer_write_string (writer, "(");
	bala_ccode_node_write ((BalaCCodeNode*) self, writer);
	bala_ccode_writer_write_string (writer, ")");
}

static void
bala_ccode_binary_expression_class_init (BalaCCodeBinaryExpressionClass * klass,
                                         gpointer klass_data)
{
	bala_ccode_binary_expression_parent_class = g_type_class_peek_parent (klass);
	((BalaCCodeNodeClass *) klass)->finalize = bala_ccode_binary_expression_finalize;
	g_type_class_adjust_private_offset (klass, &BalaCCodeBinaryExpression_private_offset);
	((BalaCCodeNodeClass *) klass)->write = (void (*) (BalaCCodeNode*, BalaCCodeWriter*)) bala_ccode_binary_expression_real_write;
	((BalaCCodeExpressionClass *) klass)->write_inner = (void (*) (BalaCCodeExpression*, BalaCCodeWriter*)) bala_ccode_binary_expression_real_write_inner;
}

static void
bala_ccode_binary_expression_instance_init (BalaCCodeBinaryExpression * self,
                                            gpointer klass)
{
	self->priv = bala_ccode_binary_expression_get_instance_private (self);
}

static void
bala_ccode_binary_expression_finalize (BalaCCodeNode * obj)
{
	BalaCCodeBinaryExpression * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BALA_TYPE_CCODE_BINARY_EXPRESSION, BalaCCodeBinaryExpression);
	_bala_ccode_node_unref0 (self->priv->_left);
	_bala_ccode_node_unref0 (self->priv->_right);
	BALA_CCODE_NODE_CLASS (bala_ccode_binary_expression_parent_class)->finalize (obj);
}

/**
 * Represents an expression with two operands in C code.
 */
static GType
bala_ccode_binary_expression_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (BalaCCodeBinaryExpressionClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bala_ccode_binary_expression_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BalaCCodeBinaryExpression), 0, (GInstanceInitFunc) bala_ccode_binary_expression_instance_init, NULL };
	GType bala_ccode_binary_expression_type_id;
	bala_ccode_binary_expression_type_id = g_type_register_static (BALA_TYPE_CCODE_EXPRESSION, "BalaCCodeBinaryExpression", &g_define_type_info, 0);
	BalaCCodeBinaryExpression_private_offset = g_type_add_instance_private (bala_ccode_binary_expression_type_id, sizeof (BalaCCodeBinaryExpressionPrivate));
	return bala_ccode_binary_expression_type_id;
}

GType
bala_ccode_binary_expression_get_type (void)
{
	static volatile gsize bala_ccode_binary_expression_type_id__volatile = 0;
	if (g_once_init_enter (&bala_ccode_binary_expression_type_id__volatile)) {
		GType bala_ccode_binary_expression_type_id;
		bala_ccode_binary_expression_type_id = bala_ccode_binary_expression_get_type_once ();
		g_once_init_leave (&bala_ccode_binary_expression_type_id__volatile, bala_ccode_binary_expression_type_id);
	}
	return bala_ccode_binary_expression_type_id__volatile;
}

static GType
bala_ccode_binary_operator_get_type_once (void)
{
	static const GEnumValue values[] = {{BALA_CCODE_BINARY_OPERATOR_PLUS, "BALA_CCODE_BINARY_OPERATOR_PLUS", "plus"}, {BALA_CCODE_BINARY_OPERATOR_MINUS, "BALA_CCODE_BINARY_OPERATOR_MINUS", "minus"}, {BALA_CCODE_BINARY_OPERATOR_MUL, "BALA_CCODE_BINARY_OPERATOR_MUL", "mul"}, {BALA_CCODE_BINARY_OPERATOR_DIV, "BALA_CCODE_BINARY_OPERATOR_DIV", "div"}, {BALA_CCODE_BINARY_OPERATOR_MOD, "BALA_CCODE_BINARY_OPERATOR_MOD", "mod"}, {BALA_CCODE_BINARY_OPERATOR_SHIFT_LEFT, "BALA_CCODE_BINARY_OPERATOR_SHIFT_LEFT", "shift-left"}, {BALA_CCODE_BINARY_OPERATOR_SHIFT_RIGHT, "BALA_CCODE_BINARY_OPERATOR_SHIFT_RIGHT", "shift-right"}, {BALA_CCODE_BINARY_OPERATOR_LESS_THAN, "BALA_CCODE_BINARY_OPERATOR_LESS_THAN", "less-than"}, {BALA_CCODE_BINARY_OPERATOR_GREATER_THAN, "BALA_CCODE_BINARY_OPERATOR_GREATER_THAN", "greater-than"}, {BALA_CCODE_BINARY_OPERATOR_LESS_THAN_OR_EQUAL, "BALA_CCODE_BINARY_OPERATOR_LESS_THAN_OR_EQUAL", "less-than-or-equal"}, {BALA_CCODE_BINARY_OPERATOR_GREATER_THAN_OR_EQUAL, "BALA_CCODE_BINARY_OPERATOR_GREATER_THAN_OR_EQUAL", "greater-than-or-equal"}, {BALA_CCODE_BINARY_OPERATOR_EQUALITY, "BALA_CCODE_BINARY_OPERATOR_EQUALITY", "equality"}, {BALA_CCODE_BINARY_OPERATOR_INEQUALITY, "BALA_CCODE_BINARY_OPERATOR_INEQUALITY", "inequality"}, {BALA_CCODE_BINARY_OPERATOR_BITWISE_AND, "BALA_CCODE_BINARY_OPERATOR_BITWISE_AND", "bitwise-and"}, {BALA_CCODE_BINARY_OPERATOR_BITWISE_OR, "BALA_CCODE_BINARY_OPERATOR_BITWISE_OR", "bitwise-or"}, {BALA_CCODE_BINARY_OPERATOR_BITWISE_XOR, "BALA_CCODE_BINARY_OPERATOR_BITWISE_XOR", "bitwise-xor"}, {BALA_CCODE_BINARY_OPERATOR_AND, "BALA_CCODE_BINARY_OPERATOR_AND", "and"}, {BALA_CCODE_BINARY_OPERATOR_OR, "BALA_CCODE_BINARY_OPERATOR_OR", "or"}, {0, NULL, NULL}};
	GType bala_ccode_binary_operator_type_id;
	bala_ccode_binary_operator_type_id = g_enum_register_static ("BalaCCodeBinaryOperator", values);
	return bala_ccode_binary_operator_type_id;
}

GType
bala_ccode_binary_operator_get_type (void)
{
	static volatile gsize bala_ccode_binary_operator_type_id__volatile = 0;
	if (g_once_init_enter (&bala_ccode_binary_operator_type_id__volatile)) {
		GType bala_ccode_binary_operator_type_id;
		bala_ccode_binary_operator_type_id = bala_ccode_binary_operator_get_type_once ();
		g_once_init_leave (&bala_ccode_binary_operator_type_id__volatile, bala_ccode_binary_operator_type_id);
	}
	return bala_ccode_binary_operator_type_id__volatile;
}

