/* balaccodecomment.c generated by balac, the Bala compiler
 * generated from balaccodecomment.bala, do not modify */

/* balaccodecomment.bala
 *
 * Copyright (C) 2006  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 */

#include "balaccode.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#define _g_free0(var) (var = (g_free (var), NULL))

struct _BalaCCodeCommentPrivate {
	gchar* _text;
};

static gint BalaCCodeComment_private_offset;
static gpointer bala_ccode_comment_parent_class = NULL;

static void bala_ccode_comment_real_write (BalaCCodeNode* base,
                                    BalaCCodeWriter* writer);
static void bala_ccode_comment_finalize (BalaCCodeNode * obj);
static GType bala_ccode_comment_get_type_once (void);

static inline gpointer
bala_ccode_comment_get_instance_private (BalaCCodeComment* self)
{
	return G_STRUCT_MEMBER_P (self, BalaCCodeComment_private_offset);
}

const gchar*
bala_ccode_comment_get_text (BalaCCodeComment* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_text;
	result = _tmp0_;
	return result;
}

void
bala_ccode_comment_set_text (BalaCCodeComment* self,
                             const gchar* value)
{
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_text);
	self->priv->_text = _tmp0_;
}

BalaCCodeComment*
bala_ccode_comment_construct (GType object_type,
                              const gchar* _text)
{
	BalaCCodeComment* self = NULL;
	g_return_val_if_fail (_text != NULL, NULL);
	self = (BalaCCodeComment*) bala_ccode_node_construct (object_type);
	bala_ccode_comment_set_text (self, _text);
	return self;
}

BalaCCodeComment*
bala_ccode_comment_new (const gchar* _text)
{
	return bala_ccode_comment_construct (BALA_TYPE_CCODE_COMMENT, _text);
}

static void
bala_ccode_comment_real_write (BalaCCodeNode* base,
                               BalaCCodeWriter* writer)
{
	BalaCCodeComment * self;
	const gchar* _tmp0_;
	self = (BalaCCodeComment*) base;
	g_return_if_fail (writer != NULL);
	_tmp0_ = self->priv->_text;
	bala_ccode_writer_write_comment (writer, _tmp0_);
}

static void
bala_ccode_comment_class_init (BalaCCodeCommentClass * klass,
                               gpointer klass_data)
{
	bala_ccode_comment_parent_class = g_type_class_peek_parent (klass);
	((BalaCCodeNodeClass *) klass)->finalize = bala_ccode_comment_finalize;
	g_type_class_adjust_private_offset (klass, &BalaCCodeComment_private_offset);
	((BalaCCodeNodeClass *) klass)->write = (void (*) (BalaCCodeNode*, BalaCCodeWriter*)) bala_ccode_comment_real_write;
}

static void
bala_ccode_comment_instance_init (BalaCCodeComment * self,
                                  gpointer klass)
{
	self->priv = bala_ccode_comment_get_instance_private (self);
}

static void
bala_ccode_comment_finalize (BalaCCodeNode * obj)
{
	BalaCCodeComment * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BALA_TYPE_CCODE_COMMENT, BalaCCodeComment);
	_g_free0 (self->priv->_text);
	BALA_CCODE_NODE_CLASS (bala_ccode_comment_parent_class)->finalize (obj);
}

/**
 * Represents a comment in the C code.
 */
static GType
bala_ccode_comment_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (BalaCCodeCommentClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bala_ccode_comment_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BalaCCodeComment), 0, (GInstanceInitFunc) bala_ccode_comment_instance_init, NULL };
	GType bala_ccode_comment_type_id;
	bala_ccode_comment_type_id = g_type_register_static (BALA_TYPE_CCODE_NODE, "BalaCCodeComment", &g_define_type_info, 0);
	BalaCCodeComment_private_offset = g_type_add_instance_private (bala_ccode_comment_type_id, sizeof (BalaCCodeCommentPrivate));
	return bala_ccode_comment_type_id;
}

GType
bala_ccode_comment_get_type (void)
{
	static volatile gsize bala_ccode_comment_type_id__volatile = 0;
	if (g_once_init_enter (&bala_ccode_comment_type_id__volatile)) {
		GType bala_ccode_comment_type_id;
		bala_ccode_comment_type_id = bala_ccode_comment_get_type_once ();
		g_once_init_leave (&bala_ccode_comment_type_id__volatile, bala_ccode_comment_type_id);
	}
	return bala_ccode_comment_type_id__volatile;
}

