/* balaexpressionstatement.c generated by balac, the Bala compiler
 * generated from balaexpressionstatement.bala, do not modify */

/* balaexpressionstatement.bala
 *
 * Copyright (C) 2006-2010  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 */

#include "bala.h"
#include <glib.h>
#include <balagee.h>
#include <glib-object.h>

#define _bala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (bala_code_node_unref (var), NULL)))

struct _BalaExpressionStatementPrivate {
	BalaExpression* _expression;
};

static gint BalaExpressionStatement_private_offset;
static gpointer bala_expression_statement_parent_class = NULL;
static BalaStatementIface * bala_expression_statement_bala_statement_parent_iface = NULL;

static void bala_expression_statement_real_accept (BalaCodeNode* base,
                                            BalaCodeVisitor* visitor);
static void bala_expression_statement_real_accept_children (BalaCodeNode* base,
                                                     BalaCodeVisitor* visitor);
static void bala_expression_statement_real_replace_expression (BalaCodeNode* base,
                                                        BalaExpression* old_node,
                                                        BalaExpression* new_node);
static gboolean bala_expression_statement_real_check (BalaCodeNode* base,
                                               BalaCodeContext* context);
static void bala_expression_statement_real_get_error_types (BalaCodeNode* base,
                                                     BalaCollection* collection,
                                                     BalaSourceReference* source_reference);
static void bala_expression_statement_real_emit (BalaCodeNode* base,
                                          BalaCodeGenerator* codegen);
static void bala_expression_statement_real_get_defined_variables (BalaCodeNode* base,
                                                           BalaCollection* collection);
static void bala_expression_statement_real_get_used_variables (BalaCodeNode* base,
                                                        BalaCollection* collection);
static void bala_expression_statement_finalize (BalaCodeNode * obj);
static GType bala_expression_statement_get_type_once (void);

static inline gpointer
bala_expression_statement_get_instance_private (BalaExpressionStatement* self)
{
	return G_STRUCT_MEMBER_P (self, BalaExpressionStatement_private_offset);
}

BalaExpression*
bala_expression_statement_get_expression (BalaExpressionStatement* self)
{
	BalaExpression* result;
	BalaExpression* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_expression;
	result = _tmp0_;
	return result;
}

static gpointer
_bala_code_node_ref0 (gpointer self)
{
	return self ? bala_code_node_ref (self) : NULL;
}

void
bala_expression_statement_set_expression (BalaExpressionStatement* self,
                                          BalaExpression* value)
{
	BalaExpression* _tmp0_;
	BalaExpression* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _bala_code_node_ref0 (value);
	_bala_code_node_unref0 (self->priv->_expression);
	self->priv->_expression = _tmp0_;
	_tmp1_ = self->priv->_expression;
	bala_code_node_set_parent_node ((BalaCodeNode*) _tmp1_, (BalaCodeNode*) self);
}

/**
 * Creates a new expression statement.
 *
 * @param expression        expression to evaluate
 * @param source_reference  reference to source code
 * @return                  newly created expression statement
 */
BalaExpressionStatement*
bala_expression_statement_construct (GType object_type,
                                     BalaExpression* expression,
                                     BalaSourceReference* source_reference)
{
	BalaExpressionStatement* self = NULL;
	g_return_val_if_fail (expression != NULL, NULL);
	self = (BalaExpressionStatement*) bala_code_node_construct (object_type);
	bala_code_node_set_source_reference ((BalaCodeNode*) self, source_reference);
	bala_expression_statement_set_expression (self, expression);
	return self;
}

BalaExpressionStatement*
bala_expression_statement_new (BalaExpression* expression,
                               BalaSourceReference* source_reference)
{
	return bala_expression_statement_construct (BALA_TYPE_EXPRESSION_STATEMENT, expression, source_reference);
}

static void
bala_expression_statement_real_accept (BalaCodeNode* base,
                                       BalaCodeVisitor* visitor)
{
	BalaExpressionStatement * self;
	self = (BalaExpressionStatement*) base;
	g_return_if_fail (visitor != NULL);
	bala_code_visitor_visit_expression_statement (visitor, self);
}

static void
bala_expression_statement_real_accept_children (BalaCodeNode* base,
                                                BalaCodeVisitor* visitor)
{
	BalaExpressionStatement * self;
	BalaExpression* _tmp0_;
	BalaExpression* _tmp1_;
	self = (BalaExpressionStatement*) base;
	g_return_if_fail (visitor != NULL);
	_tmp0_ = bala_expression_statement_get_expression (self);
	_tmp1_ = _tmp0_;
	bala_code_node_accept ((BalaCodeNode*) _tmp1_, visitor);
}

static void
bala_expression_statement_real_replace_expression (BalaCodeNode* base,
                                                   BalaExpression* old_node,
                                                   BalaExpression* new_node)
{
	BalaExpressionStatement * self;
	BalaExpression* _tmp0_;
	BalaExpression* _tmp1_;
	self = (BalaExpressionStatement*) base;
	g_return_if_fail (old_node != NULL);
	g_return_if_fail (new_node != NULL);
	_tmp0_ = bala_expression_statement_get_expression (self);
	_tmp1_ = _tmp0_;
	if (_tmp1_ == old_node) {
		bala_expression_statement_set_expression (self, new_node);
	}
}

static gboolean
bala_expression_statement_real_check (BalaCodeNode* base,
                                      BalaCodeContext* context)
{
	BalaExpressionStatement * self;
	gboolean _tmp0_;
	gboolean _tmp1_;
	BalaExpression* _tmp4_;
	BalaExpression* _tmp5_;
	gboolean _tmp10_;
	gboolean _tmp11_;
	gboolean result = FALSE;
	self = (BalaExpressionStatement*) base;
	g_return_val_if_fail (context != NULL, FALSE);
	_tmp0_ = bala_code_node_get_checked ((BalaCodeNode*) self);
	_tmp1_ = _tmp0_;
	if (_tmp1_) {
		gboolean _tmp2_;
		gboolean _tmp3_;
		_tmp2_ = bala_code_node_get_error ((BalaCodeNode*) self);
		_tmp3_ = _tmp2_;
		result = !_tmp3_;
		return result;
	}
	bala_code_node_set_checked ((BalaCodeNode*) self, TRUE);
	_tmp4_ = bala_expression_statement_get_expression (self);
	_tmp5_ = _tmp4_;
	if (!bala_code_node_check ((BalaCodeNode*) _tmp5_, context)) {
		bala_code_node_set_error ((BalaCodeNode*) self, TRUE);
		result = FALSE;
		return result;
	} else {
		BalaExpression* _tmp6_;
		BalaExpression* _tmp7_;
		_tmp6_ = bala_expression_statement_get_expression (self);
		_tmp7_ = _tmp6_;
		if (BALA_IS_LITERAL (_tmp7_)) {
			BalaSourceReference* _tmp8_;
			BalaSourceReference* _tmp9_;
			_tmp8_ = bala_code_node_get_source_reference ((BalaCodeNode*) self);
			_tmp9_ = _tmp8_;
			bala_report_error (_tmp9_, "Literal expression not allowed as statement");
			bala_code_node_set_error ((BalaCodeNode*) self, TRUE);
			result = FALSE;
			return result;
		}
	}
	_tmp10_ = bala_code_node_get_error ((BalaCodeNode*) self);
	_tmp11_ = _tmp10_;
	result = !_tmp11_;
	return result;
}

static void
bala_expression_statement_real_get_error_types (BalaCodeNode* base,
                                                BalaCollection* collection,
                                                BalaSourceReference* source_reference)
{
	BalaExpressionStatement * self;
	BalaExpression* _tmp0_;
	BalaExpression* _tmp1_;
	self = (BalaExpressionStatement*) base;
	g_return_if_fail (collection != NULL);
	_tmp0_ = bala_expression_statement_get_expression (self);
	_tmp1_ = _tmp0_;
	bala_code_node_get_error_types ((BalaCodeNode*) _tmp1_, collection, source_reference);
}

static void
bala_expression_statement_real_emit (BalaCodeNode* base,
                                     BalaCodeGenerator* codegen)
{
	BalaExpressionStatement * self;
	BalaExpression* _tmp0_;
	BalaExpression* _tmp1_;
	self = (BalaExpressionStatement*) base;
	g_return_if_fail (codegen != NULL);
	_tmp0_ = bala_expression_statement_get_expression (self);
	_tmp1_ = _tmp0_;
	bala_code_node_emit ((BalaCodeNode*) _tmp1_, codegen);
	bala_code_visitor_visit_expression_statement ((BalaCodeVisitor*) codegen, self);
}

static void
bala_expression_statement_real_get_defined_variables (BalaCodeNode* base,
                                                      BalaCollection* collection)
{
	BalaExpressionStatement * self;
	BalaExpression* _tmp0_;
	BalaExpression* _tmp1_;
	self = (BalaExpressionStatement*) base;
	g_return_if_fail (collection != NULL);
	_tmp0_ = bala_expression_statement_get_expression (self);
	_tmp1_ = _tmp0_;
	bala_code_node_get_defined_variables ((BalaCodeNode*) _tmp1_, collection);
}

static void
bala_expression_statement_real_get_used_variables (BalaCodeNode* base,
                                                   BalaCollection* collection)
{
	BalaExpressionStatement * self;
	BalaExpression* _tmp0_;
	BalaExpression* _tmp1_;
	self = (BalaExpressionStatement*) base;
	g_return_if_fail (collection != NULL);
	_tmp0_ = bala_expression_statement_get_expression (self);
	_tmp1_ = _tmp0_;
	bala_code_node_get_used_variables ((BalaCodeNode*) _tmp1_, collection);
}

static void
bala_expression_statement_class_init (BalaExpressionStatementClass * klass,
                                      gpointer klass_data)
{
	bala_expression_statement_parent_class = g_type_class_peek_parent (klass);
	((BalaCodeNodeClass *) klass)->finalize = bala_expression_statement_finalize;
	g_type_class_adjust_private_offset (klass, &BalaExpressionStatement_private_offset);
	((BalaCodeNodeClass *) klass)->accept = (void (*) (BalaCodeNode*, BalaCodeVisitor*)) bala_expression_statement_real_accept;
	((BalaCodeNodeClass *) klass)->accept_children = (void (*) (BalaCodeNode*, BalaCodeVisitor*)) bala_expression_statement_real_accept_children;
	((BalaCodeNodeClass *) klass)->replace_expression = (void (*) (BalaCodeNode*, BalaExpression*, BalaExpression*)) bala_expression_statement_real_replace_expression;
	((BalaCodeNodeClass *) klass)->check = (gboolean (*) (BalaCodeNode*, BalaCodeContext*)) bala_expression_statement_real_check;
	((BalaCodeNodeClass *) klass)->get_error_types = (void (*) (BalaCodeNode*, BalaCollection*, BalaSourceReference*)) bala_expression_statement_real_get_error_types;
	((BalaCodeNodeClass *) klass)->emit = (void (*) (BalaCodeNode*, BalaCodeGenerator*)) bala_expression_statement_real_emit;
	((BalaCodeNodeClass *) klass)->get_defined_variables = (void (*) (BalaCodeNode*, BalaCollection*)) bala_expression_statement_real_get_defined_variables;
	((BalaCodeNodeClass *) klass)->get_used_variables = (void (*) (BalaCodeNode*, BalaCollection*)) bala_expression_statement_real_get_used_variables;
}

static void
bala_expression_statement_bala_statement_interface_init (BalaStatementIface * iface,
                                                         gpointer iface_data)
{
	bala_expression_statement_bala_statement_parent_iface = g_type_interface_peek_parent (iface);
}

static void
bala_expression_statement_instance_init (BalaExpressionStatement * self,
                                         gpointer klass)
{
	self->priv = bala_expression_statement_get_instance_private (self);
}

static void
bala_expression_statement_finalize (BalaCodeNode * obj)
{
	BalaExpressionStatement * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BALA_TYPE_EXPRESSION_STATEMENT, BalaExpressionStatement);
	_bala_code_node_unref0 (self->priv->_expression);
	BALA_CODE_NODE_CLASS (bala_expression_statement_parent_class)->finalize (obj);
}

/**
 * A code statement that evaluates a given expression. The value computed by the
 * expression, if any, is discarded.
 */
static GType
bala_expression_statement_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (BalaExpressionStatementClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bala_expression_statement_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BalaExpressionStatement), 0, (GInstanceInitFunc) bala_expression_statement_instance_init, NULL };
	static const GInterfaceInfo bala_statement_info = { (GInterfaceInitFunc) bala_expression_statement_bala_statement_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType bala_expression_statement_type_id;
	bala_expression_statement_type_id = g_type_register_static (BALA_TYPE_CODE_NODE, "BalaExpressionStatement", &g_define_type_info, 0);
	g_type_add_interface_static (bala_expression_statement_type_id, BALA_TYPE_STATEMENT, &bala_statement_info);
	BalaExpressionStatement_private_offset = g_type_add_instance_private (bala_expression_statement_type_id, sizeof (BalaExpressionStatementPrivate));
	return bala_expression_statement_type_id;
}

GType
bala_expression_statement_get_type (void)
{
	static volatile gsize bala_expression_statement_type_id__volatile = 0;
	if (g_once_init_enter (&bala_expression_statement_type_id__volatile)) {
		GType bala_expression_statement_type_id;
		bala_expression_statement_type_id = bala_expression_statement_get_type_once ();
		g_once_init_leave (&bala_expression_statement_type_id__volatile, bala_expression_statement_type_id);
	}
	return bala_expression_statement_type_id__volatile;
}

