/* balaprofile.c generated by balac, the Vala compiler
 * generated from balaprofile.bala, do not modify */

/* balaprofile.bala
 *
 * Copyright (C) 2009-2010  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 */

#include "bala.h"

static GType
bala_profile_get_type_once (void)
{
	static const GEnumValue values[] = {{BALA_PROFILE_GOBJECT, "BALA_PROFILE_GOBJECT", "gobject"}, {BALA_PROFILE_POSIX, "BALA_PROFILE_POSIX", "posix"}, {0, NULL, NULL}};
	GType bala_profile_type_id;
	bala_profile_type_id = g_enum_register_static ("ValaProfile", values);
	return bala_profile_type_id;
}

GType
bala_profile_get_type (void)
{
	static volatile gsize bala_profile_type_id__volatile = 0;
	if (g_once_init_enter (&bala_profile_type_id__volatile)) {
		GType bala_profile_type_id;
		bala_profile_type_id = bala_profile_get_type_once ();
		g_once_init_leave (&bala_profile_type_id__volatile, bala_profile_type_id);
	}
	return bala_profile_type_id__volatile;
}

