/* balasubroutine.c generated by balac, the Bala compiler
 * generated from balasubroutine.bala, do not modify */

/* balasubroutine.bala
 *
 * Copyright (C) 2010  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 */

#include "bala.h"
#include <glib.h>
#include <stdlib.h>
#include <string.h>

#define _bala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (bala_code_node_unref (var), NULL)))
#define _bala_basic_block_unref0(var) ((var == NULL) ? NULL : (var = (bala_basic_block_unref (var), NULL)))

struct _BalaSubroutinePrivate {
	BalaBlock* _body;
	BalaBasicBlock* _entry_block;
	BalaBasicBlock* _return_block;
	BalaBasicBlock* _exit_block;
	BalaLocalVariable* _result_var;
};

static gint BalaSubroutine_private_offset;
static gpointer bala_subroutine_parent_class = NULL;

static void bala_subroutine_finalize (BalaCodeNode * obj);
static GType bala_subroutine_get_type_once (void);

static inline gpointer
bala_subroutine_get_instance_private (BalaSubroutine* self)
{
	return G_STRUCT_MEMBER_P (self, BalaSubroutine_private_offset);
}

BalaBasicBlock*
bala_subroutine_get_entry_block (BalaSubroutine* self)
{
	BalaBasicBlock* result;
	BalaBasicBlock* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_entry_block;
	result = _tmp0_;
	return result;
}

static gpointer
_bala_basic_block_ref0 (gpointer self)
{
	return self ? bala_basic_block_ref (self) : NULL;
}

void
bala_subroutine_set_entry_block (BalaSubroutine* self,
                                 BalaBasicBlock* value)
{
	BalaBasicBlock* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _bala_basic_block_ref0 (value);
	_bala_basic_block_unref0 (self->priv->_entry_block);
	self->priv->_entry_block = _tmp0_;
}

BalaBasicBlock*
bala_subroutine_get_return_block (BalaSubroutine* self)
{
	BalaBasicBlock* result;
	BalaBasicBlock* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_return_block;
	result = _tmp0_;
	return result;
}

void
bala_subroutine_set_return_block (BalaSubroutine* self,
                                  BalaBasicBlock* value)
{
	BalaBasicBlock* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _bala_basic_block_ref0 (value);
	_bala_basic_block_unref0 (self->priv->_return_block);
	self->priv->_return_block = _tmp0_;
}

BalaBasicBlock*
bala_subroutine_get_exit_block (BalaSubroutine* self)
{
	BalaBasicBlock* result;
	BalaBasicBlock* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_exit_block;
	result = _tmp0_;
	return result;
}

void
bala_subroutine_set_exit_block (BalaSubroutine* self,
                                BalaBasicBlock* value)
{
	BalaBasicBlock* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _bala_basic_block_ref0 (value);
	_bala_basic_block_unref0 (self->priv->_exit_block);
	self->priv->_exit_block = _tmp0_;
}

BalaLocalVariable*
bala_subroutine_get_result_var (BalaSubroutine* self)
{
	BalaLocalVariable* result;
	BalaLocalVariable* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_result_var;
	result = _tmp0_;
	return result;
}

static gpointer
_bala_code_node_ref0 (gpointer self)
{
	return self ? bala_code_node_ref (self) : NULL;
}

void
bala_subroutine_set_result_var (BalaSubroutine* self,
                                BalaLocalVariable* value)
{
	BalaLocalVariable* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _bala_code_node_ref0 (value);
	_bala_code_node_unref0 (self->priv->_result_var);
	self->priv->_result_var = _tmp0_;
}

gboolean
bala_subroutine_get_has_result (BalaSubroutine* self)
{
	g_return_val_if_fail (self != NULL, FALSE);
	return BALA_SUBROUTINE_GET_CLASS (self)->get_has_result (self);
}

BalaSubroutine*
bala_subroutine_construct (GType object_type,
                           const gchar* name,
                           BalaSourceReference* source_reference,
                           BalaComment* comment)
{
	BalaSubroutine* self = NULL;
	self = (BalaSubroutine*) bala_symbol_construct (object_type, name, source_reference, comment);
	return self;
}

BalaBlock*
bala_subroutine_get_body (BalaSubroutine* self)
{
	BalaBlock* result;
	BalaBlock* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_body;
	result = _tmp0_;
	return result;
}

void
bala_subroutine_set_body (BalaSubroutine* self,
                          BalaBlock* value)
{
	BalaBlock* _tmp0_;
	BalaBlock* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _bala_code_node_ref0 (value);
	_bala_code_node_unref0 (self->priv->_body);
	self->priv->_body = _tmp0_;
	_tmp1_ = self->priv->_body;
	if (_tmp1_ != NULL) {
		BalaBlock* _tmp2_;
		BalaScope* _tmp3_;
		BalaScope* _tmp4_;
		BalaBlock* _tmp5_;
		_tmp2_ = self->priv->_body;
		_tmp3_ = bala_symbol_get_scope ((BalaSymbol*) self);
		_tmp4_ = _tmp3_;
		bala_symbol_set_owner ((BalaSymbol*) _tmp2_, _tmp4_);
		_tmp5_ = self->priv->_body;
		bala_code_node_set_parent_node ((BalaCodeNode*) _tmp5_, (BalaCodeNode*) self);
	}
}

static void
bala_subroutine_class_init (BalaSubroutineClass * klass,
                            gpointer klass_data)
{
	bala_subroutine_parent_class = g_type_class_peek_parent (klass);
	((BalaCodeNodeClass *) klass)->finalize = bala_subroutine_finalize;
	g_type_class_adjust_private_offset (klass, &BalaSubroutine_private_offset);
}

static void
bala_subroutine_instance_init (BalaSubroutine * self,
                               gpointer klass)
{
	self->priv = bala_subroutine_get_instance_private (self);
}

static void
bala_subroutine_finalize (BalaCodeNode * obj)
{
	BalaSubroutine * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BALA_TYPE_SUBROUTINE, BalaSubroutine);
	_bala_code_node_unref0 (self->priv->_body);
	_bala_basic_block_unref0 (self->priv->_entry_block);
	_bala_basic_block_unref0 (self->priv->_return_block);
	_bala_basic_block_unref0 (self->priv->_exit_block);
	_bala_code_node_unref0 (self->priv->_result_var);
	BALA_CODE_NODE_CLASS (bala_subroutine_parent_class)->finalize (obj);
}

static GType
bala_subroutine_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (BalaSubroutineClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bala_subroutine_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BalaSubroutine), 0, (GInstanceInitFunc) bala_subroutine_instance_init, NULL };
	GType bala_subroutine_type_id;
	bala_subroutine_type_id = g_type_register_static (BALA_TYPE_SYMBOL, "BalaSubroutine", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
	BalaSubroutine_private_offset = g_type_add_instance_private (bala_subroutine_type_id, sizeof (BalaSubroutinePrivate));
	return bala_subroutine_type_id;
}

GType
bala_subroutine_get_type (void)
{
	static volatile gsize bala_subroutine_type_id__volatile = 0;
	if (g_once_init_enter (&bala_subroutine_type_id__volatile)) {
		GType bala_subroutine_type_id;
		bala_subroutine_type_id = bala_subroutine_get_type_once ();
		g_once_init_leave (&bala_subroutine_type_id__volatile, bala_subroutine_type_id);
	}
	return bala_subroutine_type_id__volatile;
}

