/* balacharacterliteral.c generated by balac, the Bala compiler
 * generated from balacharacterliteral.bala, do not modify */

/* balacharacterliteral.bala
 *
 * Copyright (C) 2006-2010  Jürg Billeter
 * Copyright (C) 2006-2009  Raffaele Sandrini
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 *	Raffaele Sandrini <raffaele@sandrini.ch>
 */

#include "bala.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>

#define _g_free0(var) (var = (g_free (var), NULL))
#define _bala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (bala_code_node_unref (var), NULL)))

struct _BalaCharacterLiteralPrivate {
	gchar* _value;
};

static gint BalaCharacterLiteral_private_offset;
static gpointer bala_character_literal_parent_class = NULL;

static void bala_character_literal_real_accept (BalaCodeNode* base,
                                         BalaCodeVisitor* visitor);
static gboolean bala_character_literal_real_is_pure (BalaExpression* base);
static gchar* bala_character_literal_real_to_string (BalaCodeNode* base);
static gboolean bala_character_literal_real_check (BalaCodeNode* base,
                                            BalaCodeContext* context);
static void bala_character_literal_real_emit (BalaCodeNode* base,
                                       BalaCodeGenerator* codegen);
static void bala_character_literal_finalize (BalaCodeNode * obj);
static GType bala_character_literal_get_type_once (void);

static inline gpointer
bala_character_literal_get_instance_private (BalaCharacterLiteral* self)
{
	return G_STRUCT_MEMBER_P (self, BalaCharacterLiteral_private_offset);
}

const gchar*
bala_character_literal_get_value (BalaCharacterLiteral* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_value;
	result = _tmp0_;
	return result;
}

void
bala_character_literal_set_value (BalaCharacterLiteral* self,
                                  const gchar* value)
{
	gchar* _tmp0_;
	g_return_if_fail (self != NULL);
	_tmp0_ = g_strdup (value);
	_g_free0 (self->priv->_value);
	self->priv->_value = _tmp0_;
	if (!g_utf8_validate (value, (gssize) -1, NULL)) {
		bala_code_node_set_error ((BalaCodeNode*) self, TRUE);
	}
}

/**
 * Creates a new character literal.
 *
 * @param c      character
 * @param source reference to source code
 * @return       newly created character literal
 */
BalaCharacterLiteral*
bala_character_literal_construct (GType object_type,
                                  const gchar* c,
                                  BalaSourceReference* source)
{
	BalaCharacterLiteral* self = NULL;
	g_return_val_if_fail (c != NULL, NULL);
	self = (BalaCharacterLiteral*) bala_literal_construct (object_type);
	bala_character_literal_set_value (self, c);
	bala_code_node_set_source_reference ((BalaCodeNode*) self, source);
	return self;
}

BalaCharacterLiteral*
bala_character_literal_new (const gchar* c,
                            BalaSourceReference* source)
{
	return bala_character_literal_construct (BALA_TYPE_CHARACTER_LITERAL, c, source);
}

static void
bala_character_literal_real_accept (BalaCodeNode* base,
                                    BalaCodeVisitor* visitor)
{
	BalaCharacterLiteral * self;
	self = (BalaCharacterLiteral*) base;
	g_return_if_fail (visitor != NULL);
	bala_code_visitor_visit_character_literal (visitor, self);
	bala_code_visitor_visit_expression (visitor, (BalaExpression*) self);
}

/**
 * Returns the unicode character value this character literal
 * represents.
 *
 * @return unicode character value
 */
static gunichar
string_get_char (const gchar* self,
                 glong index)
{
	gunichar result = 0U;
	g_return_val_if_fail (self != NULL, 0U);
	result = g_utf8_get_char (((gchar*) self) + index);
	return result;
}

gunichar
bala_character_literal_get_char (BalaCharacterLiteral* self)
{
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	const gchar* _tmp2_;
	gunichar result = 0U;
	g_return_val_if_fail (self != NULL, 0U);
	_tmp0_ = bala_character_literal_get_value (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_utf8_next_char (_tmp1_);
	result = string_get_char (_tmp2_, (glong) 0);
	return result;
}

static gboolean
bala_character_literal_real_is_pure (BalaExpression* base)
{
	BalaCharacterLiteral * self;
	gboolean result = FALSE;
	self = (BalaCharacterLiteral*) base;
	result = TRUE;
	return result;
}

static gchar*
bala_character_literal_real_to_string (BalaCodeNode* base)
{
	BalaCharacterLiteral * self;
	const gchar* _tmp0_;
	const gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* result = NULL;
	self = (BalaCharacterLiteral*) base;
	_tmp0_ = bala_character_literal_get_value (self);
	_tmp1_ = _tmp0_;
	_tmp2_ = g_strdup (_tmp1_);
	result = _tmp2_;
	return result;
}

static gboolean
bala_character_literal_real_check (BalaCodeNode* base,
                                   BalaCodeContext* context)
{
	BalaCharacterLiteral * self;
	gboolean _tmp0_;
	gboolean _tmp1_;
	gboolean _tmp20_;
	gboolean _tmp21_;
	gboolean result = FALSE;
	self = (BalaCharacterLiteral*) base;
	g_return_val_if_fail (context != NULL, FALSE);
	_tmp0_ = bala_code_node_get_checked ((BalaCodeNode*) self);
	_tmp1_ = _tmp0_;
	if (_tmp1_) {
		gboolean _tmp2_;
		gboolean _tmp3_;
		_tmp2_ = bala_code_node_get_error ((BalaCodeNode*) self);
		_tmp3_ = _tmp2_;
		result = !_tmp3_;
		return result;
	}
	bala_code_node_set_checked ((BalaCodeNode*) self, TRUE);
	if (bala_character_literal_get_char (self) < ((gunichar) 128)) {
		BalaNamespace* _tmp4_;
		BalaNamespace* _tmp5_;
		BalaScope* _tmp6_;
		BalaScope* _tmp7_;
		BalaSymbol* _tmp8_;
		BalaStruct* _tmp9_;
		BalaIntegerType* _tmp10_;
		BalaIntegerType* _tmp11_;
		_tmp4_ = bala_code_context_get_root (context);
		_tmp5_ = _tmp4_;
		_tmp6_ = bala_symbol_get_scope ((BalaSymbol*) _tmp5_);
		_tmp7_ = _tmp6_;
		_tmp8_ = bala_scope_lookup (_tmp7_, "char");
		_tmp9_ = G_TYPE_CHECK_INSTANCE_CAST (_tmp8_, BALA_TYPE_STRUCT, BalaStruct);
		_tmp10_ = bala_integer_type_new (_tmp9_, NULL, NULL);
		_tmp11_ = _tmp10_;
		bala_expression_set_value_type ((BalaExpression*) self, (BalaDataType*) _tmp11_);
		_bala_code_node_unref0 (_tmp11_);
		_bala_code_node_unref0 (_tmp9_);
	} else {
		BalaNamespace* _tmp12_;
		BalaNamespace* _tmp13_;
		BalaScope* _tmp14_;
		BalaScope* _tmp15_;
		BalaSymbol* _tmp16_;
		BalaStruct* _tmp17_;
		BalaIntegerType* _tmp18_;
		BalaIntegerType* _tmp19_;
		_tmp12_ = bala_code_context_get_root (context);
		_tmp13_ = _tmp12_;
		_tmp14_ = bala_symbol_get_scope ((BalaSymbol*) _tmp13_);
		_tmp15_ = _tmp14_;
		_tmp16_ = bala_scope_lookup (_tmp15_, "unichar");
		_tmp17_ = G_TYPE_CHECK_INSTANCE_CAST (_tmp16_, BALA_TYPE_STRUCT, BalaStruct);
		_tmp18_ = bala_integer_type_new (_tmp17_, NULL, NULL);
		_tmp19_ = _tmp18_;
		bala_expression_set_value_type ((BalaExpression*) self, (BalaDataType*) _tmp19_);
		_bala_code_node_unref0 (_tmp19_);
		_bala_code_node_unref0 (_tmp17_);
	}
	_tmp20_ = bala_code_node_get_error ((BalaCodeNode*) self);
	_tmp21_ = _tmp20_;
	result = !_tmp21_;
	return result;
}

static void
bala_character_literal_real_emit (BalaCodeNode* base,
                                  BalaCodeGenerator* codegen)
{
	BalaCharacterLiteral * self;
	self = (BalaCharacterLiteral*) base;
	g_return_if_fail (codegen != NULL);
	bala_code_visitor_visit_character_literal ((BalaCodeVisitor*) codegen, self);
	bala_code_visitor_visit_expression ((BalaCodeVisitor*) codegen, (BalaExpression*) self);
}

static void
bala_character_literal_class_init (BalaCharacterLiteralClass * klass,
                                   gpointer klass_data)
{
	bala_character_literal_parent_class = g_type_class_peek_parent (klass);
	((BalaCodeNodeClass *) klass)->finalize = bala_character_literal_finalize;
	g_type_class_adjust_private_offset (klass, &BalaCharacterLiteral_private_offset);
	((BalaCodeNodeClass *) klass)->accept = (void (*) (BalaCodeNode*, BalaCodeVisitor*)) bala_character_literal_real_accept;
	((BalaExpressionClass *) klass)->is_pure = (gboolean (*) (BalaExpression*)) bala_character_literal_real_is_pure;
	((BalaCodeNodeClass *) klass)->to_string = (gchar* (*) (BalaCodeNode*)) bala_character_literal_real_to_string;
	((BalaCodeNodeClass *) klass)->check = (gboolean (*) (BalaCodeNode*, BalaCodeContext*)) bala_character_literal_real_check;
	((BalaCodeNodeClass *) klass)->emit = (void (*) (BalaCodeNode*, BalaCodeGenerator*)) bala_character_literal_real_emit;
}

static void
bala_character_literal_instance_init (BalaCharacterLiteral * self,
                                      gpointer klass)
{
	self->priv = bala_character_literal_get_instance_private (self);
}

static void
bala_character_literal_finalize (BalaCodeNode * obj)
{
	BalaCharacterLiteral * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BALA_TYPE_CHARACTER_LITERAL, BalaCharacterLiteral);
	_g_free0 (self->priv->_value);
	BALA_CODE_NODE_CLASS (bala_character_literal_parent_class)->finalize (obj);
}

/**
 * Represents a single literal character.
 */
static GType
bala_character_literal_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (BalaCharacterLiteralClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bala_character_literal_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BalaCharacterLiteral), 0, (GInstanceInitFunc) bala_character_literal_instance_init, NULL };
	GType bala_character_literal_type_id;
	bala_character_literal_type_id = g_type_register_static (BALA_TYPE_LITERAL, "BalaCharacterLiteral", &g_define_type_info, 0);
	BalaCharacterLiteral_private_offset = g_type_add_instance_private (bala_character_literal_type_id, sizeof (BalaCharacterLiteralPrivate));
	return bala_character_literal_type_id;
}

GType
bala_character_literal_get_type (void)
{
	static volatile gsize bala_character_literal_type_id__volatile = 0;
	if (g_once_init_enter (&bala_character_literal_type_id__volatile)) {
		GType bala_character_literal_type_id;
		bala_character_literal_type_id = bala_character_literal_get_type_once ();
		g_once_init_leave (&bala_character_literal_type_id__volatile, bala_character_literal_type_id);
	}
	return bala_character_literal_type_id__volatile;
}

