/* balaliteral.c generated by balac, the Bala compiler
 * generated from balaliteral.bala, do not modify */

/* balaliteral.bala
 *
 * Copyright (C) 2006-2008  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 */

#include "bala.h"
#include <glib.h>

static gpointer bala_literal_parent_class = NULL;

static gboolean bala_literal_real_is_constant (BalaExpression* base);
static gboolean bala_literal_real_is_pure (BalaExpression* base);
static GType bala_literal_get_type_once (void);

static gboolean
bala_literal_real_is_constant (BalaExpression* base)
{
	BalaLiteral * self;
	gboolean result = FALSE;
	self = (BalaLiteral*) base;
	result = TRUE;
	return result;
}

static gboolean
bala_literal_real_is_pure (BalaExpression* base)
{
	BalaLiteral * self;
	gboolean result = FALSE;
	self = (BalaLiteral*) base;
	result = TRUE;
	return result;
}

BalaLiteral*
bala_literal_construct (GType object_type)
{
	BalaLiteral* self = NULL;
	self = (BalaLiteral*) bala_expression_construct (object_type);
	return self;
}

static void
bala_literal_class_init (BalaLiteralClass * klass,
                         gpointer klass_data)
{
	bala_literal_parent_class = g_type_class_peek_parent (klass);
	((BalaExpressionClass *) klass)->is_constant = (gboolean (*) (BalaExpression*)) bala_literal_real_is_constant;
	((BalaExpressionClass *) klass)->is_pure = (gboolean (*) (BalaExpression*)) bala_literal_real_is_pure;
}

static void
bala_literal_instance_init (BalaLiteral * self,
                            gpointer klass)
{
}

/**
 * Base class for all literals in the source code.
 */
static GType
bala_literal_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (BalaLiteralClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bala_literal_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BalaLiteral), 0, (GInstanceInitFunc) bala_literal_instance_init, NULL };
	GType bala_literal_type_id;
	bala_literal_type_id = g_type_register_static (BALA_TYPE_EXPRESSION, "BalaLiteral", &g_define_type_info, G_TYPE_FLAG_ABSTRACT);
	return bala_literal_type_id;
}

GType
bala_literal_get_type (void)
{
	static volatile gsize bala_literal_type_id__volatile = 0;
	if (g_once_init_enter (&bala_literal_type_id__volatile)) {
		GType bala_literal_type_id;
		bala_literal_type_id = bala_literal_get_type_once ();
		g_once_init_leave (&bala_literal_type_id__volatile, bala_literal_type_id);
	}
	return bala_literal_type_id__volatile;
}

