/* balaarraylengthfield.c generated by balac, the Bala compiler
 * generated from balaarraylengthfield.bala, do not modify */

/* balaarraylengthfield.bala
 *
 * Copyright (C) 2007-2008  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 */

#include "bala.h"
#include <glib.h>

#define _bala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (bala_code_node_unref (var), NULL)))

static gpointer bala_array_length_field_parent_class = NULL;

static GType bala_array_length_field_get_type_once (void);

/**
 * Creates a new array length field.
 *
 * @return newly created field
 */
BalaArrayLengthField*
bala_array_length_field_construct (GType object_type,
                                   BalaSourceReference* source_reference)
{
	BalaArrayLengthField* self = NULL;
	BalaInvalidType* _tmp0_;
	BalaInvalidType* _tmp1_;
	_tmp0_ = bala_invalid_type_new ();
	_tmp1_ = _tmp0_;
	self = (BalaArrayLengthField*) bala_field_construct (object_type, "length", (BalaDataType*) _tmp1_, NULL, source_reference, NULL);
	_bala_code_node_unref0 (_tmp1_);
	bala_symbol_set_external ((BalaSymbol*) self, TRUE);
	return self;
}

BalaArrayLengthField*
bala_array_length_field_new (BalaSourceReference* source_reference)
{
	return bala_array_length_field_construct (BALA_TYPE_ARRAY_LENGTH_FIELD, source_reference);
}

static void
bala_array_length_field_class_init (BalaArrayLengthFieldClass * klass,
                                    gpointer klass_data)
{
	bala_array_length_field_parent_class = g_type_class_peek_parent (klass);
}

static void
bala_array_length_field_instance_init (BalaArrayLengthField * self,
                                       gpointer klass)
{
}

/**
 * Represents the Array.length field.
 */
static GType
bala_array_length_field_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (BalaArrayLengthFieldClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bala_array_length_field_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BalaArrayLengthField), 0, (GInstanceInitFunc) bala_array_length_field_instance_init, NULL };
	GType bala_array_length_field_type_id;
	bala_array_length_field_type_id = g_type_register_static (BALA_TYPE_FIELD, "BalaArrayLengthField", &g_define_type_info, 0);
	return bala_array_length_field_type_id;
}

GType
bala_array_length_field_get_type (void)
{
	static volatile gsize bala_array_length_field_type_id__volatile = 0;
	if (g_once_init_enter (&bala_array_length_field_type_id__volatile)) {
		GType bala_array_length_field_type_id;
		bala_array_length_field_type_id = bala_array_length_field_get_type_once ();
		g_once_init_leave (&bala_array_length_field_type_id__volatile, bala_array_length_field_type_id);
	}
	return bala_array_length_field_type_id__volatile;
}

