/* balaloop.c generated by balac, the Bala compiler
 * generated from balaloop.bala, do not modify */

/* balaloop.bala
 *
 * Copyright (C) 2009-2010  Jürg Billeter
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.

 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.

 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Jürg Billeter <j@bitron.ch>
 */

#include "bala.h"
#include <balagee.h>
#include <glib-object.h>
#include <glib.h>

#define _bala_code_node_unref0(var) ((var == NULL) ? NULL : (var = (bala_code_node_unref (var), NULL)))

struct _BalaLoopPrivate {
	BalaBlock* _body;
};

static gint BalaLoop_private_offset;
static gpointer bala_loop_parent_class = NULL;
static BalaStatementIface * bala_loop_bala_statement_parent_iface = NULL;

static void bala_loop_real_accept (BalaCodeNode* base,
                            BalaCodeVisitor* visitor);
static void bala_loop_real_accept_children (BalaCodeNode* base,
                                     BalaCodeVisitor* visitor);
static void bala_loop_real_get_error_types (BalaCodeNode* base,
                                     BalaCollection* collection,
                                     BalaSourceReference* source_reference);
static gboolean bala_loop_real_check (BalaCodeNode* base,
                               BalaCodeContext* context);
static void bala_loop_real_emit (BalaCodeNode* base,
                          BalaCodeGenerator* codegen);
static void bala_loop_finalize (BalaCodeNode * obj);
static GType bala_loop_get_type_once (void);

static inline gpointer
bala_loop_get_instance_private (BalaLoop* self)
{
	return G_STRUCT_MEMBER_P (self, BalaLoop_private_offset);
}

BalaBlock*
bala_loop_get_body (BalaLoop* self)
{
	BalaBlock* result;
	BalaBlock* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_body;
	result = _tmp0_;
	return result;
}

static gpointer
_bala_code_node_ref0 (gpointer self)
{
	return self ? bala_code_node_ref (self) : NULL;
}

void
bala_loop_set_body (BalaLoop* self,
                    BalaBlock* value)
{
	BalaBlock* _tmp0_;
	BalaBlock* _tmp1_;
	g_return_if_fail (self != NULL);
	_tmp0_ = _bala_code_node_ref0 (value);
	_bala_code_node_unref0 (self->priv->_body);
	self->priv->_body = _tmp0_;
	_tmp1_ = self->priv->_body;
	bala_code_node_set_parent_node ((BalaCodeNode*) _tmp1_, (BalaCodeNode*) self);
}

/**
 * Creates a new loop.
 *
 * @param body             loop body
 * @param source_reference reference to source code
 * @return                 newly created while statement
 */
BalaLoop*
bala_loop_construct (GType object_type,
                     BalaBlock* body,
                     BalaSourceReference* source_reference)
{
	BalaLoop* self = NULL;
	g_return_val_if_fail (body != NULL, NULL);
	self = (BalaLoop*) bala_code_node_construct (object_type);
	bala_loop_set_body (self, body);
	bala_code_node_set_source_reference ((BalaCodeNode*) self, source_reference);
	return self;
}

BalaLoop*
bala_loop_new (BalaBlock* body,
               BalaSourceReference* source_reference)
{
	return bala_loop_construct (BALA_TYPE_LOOP, body, source_reference);
}

static void
bala_loop_real_accept (BalaCodeNode* base,
                       BalaCodeVisitor* visitor)
{
	BalaLoop * self;
	self = (BalaLoop*) base;
	g_return_if_fail (visitor != NULL);
	bala_code_visitor_visit_loop (visitor, self);
}

static void
bala_loop_real_accept_children (BalaCodeNode* base,
                                BalaCodeVisitor* visitor)
{
	BalaLoop * self;
	BalaBlock* _tmp0_;
	BalaBlock* _tmp1_;
	self = (BalaLoop*) base;
	g_return_if_fail (visitor != NULL);
	_tmp0_ = bala_loop_get_body (self);
	_tmp1_ = _tmp0_;
	bala_code_node_accept ((BalaCodeNode*) _tmp1_, visitor);
}

static void
bala_loop_real_get_error_types (BalaCodeNode* base,
                                BalaCollection* collection,
                                BalaSourceReference* source_reference)
{
	BalaLoop * self;
	BalaBlock* _tmp0_;
	BalaBlock* _tmp1_;
	self = (BalaLoop*) base;
	g_return_if_fail (collection != NULL);
	_tmp0_ = bala_loop_get_body (self);
	_tmp1_ = _tmp0_;
	bala_code_node_get_error_types ((BalaCodeNode*) _tmp1_, collection, source_reference);
}

static gboolean
bala_loop_real_check (BalaCodeNode* base,
                      BalaCodeContext* context)
{
	BalaLoop * self;
	gboolean _tmp0_;
	gboolean _tmp1_;
	BalaBlock* _tmp4_;
	BalaBlock* _tmp5_;
	gboolean _tmp6_;
	gboolean _tmp7_;
	gboolean result = FALSE;
	self = (BalaLoop*) base;
	g_return_val_if_fail (context != NULL, FALSE);
	_tmp0_ = bala_code_node_get_checked ((BalaCodeNode*) self);
	_tmp1_ = _tmp0_;
	if (_tmp1_) {
		gboolean _tmp2_;
		gboolean _tmp3_;
		_tmp2_ = bala_code_node_get_error ((BalaCodeNode*) self);
		_tmp3_ = _tmp2_;
		result = !_tmp3_;
		return result;
	}
	bala_code_node_set_checked ((BalaCodeNode*) self, TRUE);
	_tmp4_ = bala_loop_get_body (self);
	_tmp5_ = _tmp4_;
	bala_code_node_check ((BalaCodeNode*) _tmp5_, context);
	_tmp6_ = bala_code_node_get_error ((BalaCodeNode*) self);
	_tmp7_ = _tmp6_;
	result = !_tmp7_;
	return result;
}

static void
bala_loop_real_emit (BalaCodeNode* base,
                     BalaCodeGenerator* codegen)
{
	BalaLoop * self;
	self = (BalaLoop*) base;
	g_return_if_fail (codegen != NULL);
	bala_code_visitor_visit_loop ((BalaCodeVisitor*) codegen, self);
}

static void
bala_loop_class_init (BalaLoopClass * klass,
                      gpointer klass_data)
{
	bala_loop_parent_class = g_type_class_peek_parent (klass);
	((BalaCodeNodeClass *) klass)->finalize = bala_loop_finalize;
	g_type_class_adjust_private_offset (klass, &BalaLoop_private_offset);
	((BalaCodeNodeClass *) klass)->accept = (void (*) (BalaCodeNode*, BalaCodeVisitor*)) bala_loop_real_accept;
	((BalaCodeNodeClass *) klass)->accept_children = (void (*) (BalaCodeNode*, BalaCodeVisitor*)) bala_loop_real_accept_children;
	((BalaCodeNodeClass *) klass)->get_error_types = (void (*) (BalaCodeNode*, BalaCollection*, BalaSourceReference*)) bala_loop_real_get_error_types;
	((BalaCodeNodeClass *) klass)->check = (gboolean (*) (BalaCodeNode*, BalaCodeContext*)) bala_loop_real_check;
	((BalaCodeNodeClass *) klass)->emit = (void (*) (BalaCodeNode*, BalaCodeGenerator*)) bala_loop_real_emit;
}

static void
bala_loop_bala_statement_interface_init (BalaStatementIface * iface,
                                         gpointer iface_data)
{
	bala_loop_bala_statement_parent_iface = g_type_interface_peek_parent (iface);
}

static void
bala_loop_instance_init (BalaLoop * self,
                         gpointer klass)
{
	self->priv = bala_loop_get_instance_private (self);
}

static void
bala_loop_finalize (BalaCodeNode * obj)
{
	BalaLoop * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BALA_TYPE_LOOP, BalaLoop);
	_bala_code_node_unref0 (self->priv->_body);
	BALA_CODE_NODE_CLASS (bala_loop_parent_class)->finalize (obj);
}

/**
 * Represents an endless loop.
 */
static GType
bala_loop_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (BalaLoopClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) bala_loop_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (BalaLoop), 0, (GInstanceInitFunc) bala_loop_instance_init, NULL };
	static const GInterfaceInfo bala_statement_info = { (GInterfaceInitFunc) bala_loop_bala_statement_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType bala_loop_type_id;
	bala_loop_type_id = g_type_register_static (BALA_TYPE_CODE_NODE, "BalaLoop", &g_define_type_info, 0);
	g_type_add_interface_static (bala_loop_type_id, BALA_TYPE_STATEMENT, &bala_statement_info);
	BalaLoop_private_offset = g_type_add_instance_private (bala_loop_type_id, sizeof (BalaLoopPrivate));
	return bala_loop_type_id;
}

GType
bala_loop_get_type (void)
{
	static volatile gsize bala_loop_type_id__volatile = 0;
	if (g_once_init_enter (&bala_loop_type_id__volatile)) {
		GType bala_loop_type_id;
		bala_loop_type_id = bala_loop_get_type_once ();
		g_once_init_leave (&bala_loop_type_id__volatile, bala_loop_type_id);
	}
	return bala_loop_type_id__volatile;
}

