/* text.c generated by balac, the Vala compiler
 * generated from text.bala, do not modify */

/* text.bala
 *
 * Copyright (C) 2008-2009 Didier Villevalois
 * Copyright (C) 2008-2012 Florian Brosch
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301  USA
 *
 * Author:
 * 	Didier 'Ptitjes Villevalois <ptitjes@free.fr>
 */

#include "baladoc.h"
#include <stdlib.h>
#include <string.h>
#include <glib.h>

enum  {
	BALADOC_CONTENT_TEXT_0_PROPERTY,
	BALADOC_CONTENT_TEXT_CONTENT_PROPERTY,
	BALADOC_CONTENT_TEXT_NUM_PROPERTIES
};
static GParamSpec* baladoc_content_text_properties[BALADOC_CONTENT_TEXT_NUM_PROPERTIES];
#define _g_free0(var) (var = (g_free (var), NULL))

struct _ValadocContentTextPrivate {
	gchar* _content;
};

static gint ValadocContentText_private_offset;
static gpointer baladoc_content_text_parent_class = NULL;
static ValadocContentInlineIface * baladoc_content_text_baladoc_content_inline_parent_iface = NULL;

G_GNUC_INTERNAL ValadocContentText* baladoc_content_text_new (const gchar* text);
G_GNUC_INTERNAL ValadocContentText* baladoc_content_text_construct (GType object_type,
                                                    const gchar* text);
static void baladoc_content_text_real_check (ValadocContentContentElement* base,
                                      ValadocApiTree* api_root,
                                      ValadocApiNode* container,
                                      const gchar* file_path,
                                      ValadocErrorReporter* reporter,
                                      ValadocSettings* settings);
static void baladoc_content_text_real_accept (ValadocContentContentElement* base,
                                       ValadocContentContentVisitor* visitor);
static gboolean baladoc_content_text_real_is_empty (ValadocContentContentElement* base);
static ValadocContentContentElement* baladoc_content_text_real_copy (ValadocContentContentElement* base,
                                                              ValadocContentContentElement* new_parent);
G_GNUC_INTERNAL void baladoc_content_content_element_set_parent (ValadocContentContentElement* self,
                                                 ValadocContentContentElement* value);
static GObject * baladoc_content_text_constructor (GType type,
                                            guint n_construct_properties,
                                            GObjectConstructParam * construct_properties);
static void baladoc_content_text_finalize (GObject * obj);
static GType baladoc_content_text_get_type_once (void);
static void _bala_baladoc_content_text_get_property (GObject * object,
                                              guint property_id,
                                              GValue * value,
                                              GParamSpec * pspec);
static void _bala_baladoc_content_text_set_property (GObject * object,
                                              guint property_id,
                                              const GValue * value,
                                              GParamSpec * pspec);

static inline gpointer
baladoc_content_text_get_instance_private (ValadocContentText* self)
{
	return G_STRUCT_MEMBER_P (self, ValadocContentText_private_offset);
}

const gchar*
baladoc_content_text_get_content (ValadocContentText* self)
{
	const gchar* result;
	const gchar* _tmp0_;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_content;
	result = _tmp0_;
	return result;
}

void
baladoc_content_text_set_content (ValadocContentText* self,
                                  const gchar* value)
{
	gchar* old_value;
	g_return_if_fail (self != NULL);
	old_value = baladoc_content_text_get_content (self);
	if (g_strcmp0 (value, old_value) != 0) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (value);
		_g_free0 (self->priv->_content);
		self->priv->_content = _tmp0_;
		g_object_notify_by_pspec ((GObject *) self, baladoc_content_text_properties[BALADOC_CONTENT_TEXT_CONTENT_PROPERTY]);
	}
}

G_GNUC_INTERNAL ValadocContentText*
baladoc_content_text_construct (GType object_type,
                                const gchar* text)
{
	ValadocContentText * self = NULL;
	self = (ValadocContentText*) baladoc_content_content_element_construct (object_type);
	if (text != NULL) {
		gchar* _tmp0_;
		_tmp0_ = g_strdup (text);
		_g_free0 (self->priv->_content);
		self->priv->_content = _tmp0_;
	}
	return self;
}

G_GNUC_INTERNAL ValadocContentText*
baladoc_content_text_new (const gchar* text)
{
	return baladoc_content_text_construct (BALADOC_CONTENT_TYPE_TEXT, text);
}

static void
baladoc_content_text_real_check (ValadocContentContentElement* base,
                                 ValadocApiTree* api_root,
                                 ValadocApiNode* container,
                                 const gchar* file_path,
                                 ValadocErrorReporter* reporter,
                                 ValadocSettings* settings)
{
	ValadocContentText * self;
	self = (ValadocContentText*) base;
	g_return_if_fail (api_root != NULL);
	g_return_if_fail (container != NULL);
	g_return_if_fail (file_path != NULL);
	g_return_if_fail (reporter != NULL);
	g_return_if_fail (settings != NULL);
}

static void
baladoc_content_text_real_accept (ValadocContentContentElement* base,
                                  ValadocContentContentVisitor* visitor)
{
	ValadocContentText * self;
	self = (ValadocContentText*) base;
	g_return_if_fail (visitor != NULL);
	baladoc_content_content_visitor_visit_text (visitor, self);
}

static gboolean
baladoc_content_text_real_is_empty (ValadocContentContentElement* base)
{
	ValadocContentText * self;
	const gchar* _tmp0_;
	gboolean result = FALSE;
	self = (ValadocContentText*) base;
	_tmp0_ = self->priv->_content;
	result = g_strcmp0 (_tmp0_, "") == 0;
	return result;
}

static ValadocContentContentElement*
baladoc_content_text_real_copy (ValadocContentContentElement* base,
                                ValadocContentContentElement* new_parent)
{
	ValadocContentText * self;
	ValadocContentText* text = NULL;
	const gchar* _tmp0_;
	ValadocContentText* _tmp1_;
	ValadocContentContentElement* result = NULL;
	self = (ValadocContentText*) base;
	_tmp0_ = self->priv->_content;
	_tmp1_ = baladoc_content_text_new (_tmp0_);
	text = _tmp1_;
	baladoc_content_content_element_set_parent ((ValadocContentContentElement*) text, new_parent);
	result = (ValadocContentContentElement*) text;
	return result;
}

static GObject *
baladoc_content_text_constructor (GType type,
                                  guint n_construct_properties,
                                  GObjectConstructParam * construct_properties)
{
	GObject * obj;
	GObjectClass * parent_class;
	ValadocContentText * self;
	gchar* _tmp0_;
	parent_class = G_OBJECT_CLASS (baladoc_content_text_parent_class);
	obj = parent_class->constructor (type, n_construct_properties, construct_properties);
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BALADOC_CONTENT_TYPE_TEXT, ValadocContentText);
	_tmp0_ = g_strdup ("");
	_g_free0 (self->priv->_content);
	self->priv->_content = _tmp0_;
	return obj;
}

static void
baladoc_content_text_class_init (ValadocContentTextClass * klass,
                                 gpointer klass_data)
{
	baladoc_content_text_parent_class = g_type_class_peek_parent (klass);
	g_type_class_adjust_private_offset (klass, &ValadocContentText_private_offset);
	((ValadocContentContentElementClass *) klass)->check = (void (*) (ValadocContentContentElement*, ValadocApiTree*, ValadocApiNode*, const gchar*, ValadocErrorReporter*, ValadocSettings*)) baladoc_content_text_real_check;
	((ValadocContentContentElementClass *) klass)->accept = (void (*) (ValadocContentContentElement*, ValadocContentContentVisitor*)) baladoc_content_text_real_accept;
	((ValadocContentContentElementClass *) klass)->is_empty = (gboolean (*) (ValadocContentContentElement*)) baladoc_content_text_real_is_empty;
	((ValadocContentContentElementClass *) klass)->copy = (ValadocContentContentElement* (*) (ValadocContentContentElement*, ValadocContentContentElement*)) baladoc_content_text_real_copy;
	G_OBJECT_CLASS (klass)->get_property = _bala_baladoc_content_text_get_property;
	G_OBJECT_CLASS (klass)->set_property = _bala_baladoc_content_text_set_property;
	G_OBJECT_CLASS (klass)->constructor = baladoc_content_text_constructor;
	G_OBJECT_CLASS (klass)->finalize = baladoc_content_text_finalize;
	g_object_class_install_property (G_OBJECT_CLASS (klass), BALADOC_CONTENT_TEXT_CONTENT_PROPERTY, baladoc_content_text_properties[BALADOC_CONTENT_TEXT_CONTENT_PROPERTY] = g_param_spec_string ("content", "content", "content", NULL, G_PARAM_STATIC_STRINGS | G_PARAM_READABLE | G_PARAM_WRITABLE));
}

static void
baladoc_content_text_baladoc_content_inline_interface_init (ValadocContentInlineIface * iface,
                                                            gpointer iface_data)
{
	baladoc_content_text_baladoc_content_inline_parent_iface = g_type_interface_peek_parent (iface);
}

static void
baladoc_content_text_instance_init (ValadocContentText * self,
                                    gpointer klass)
{
	self->priv = baladoc_content_text_get_instance_private (self);
}

static void
baladoc_content_text_finalize (GObject * obj)
{
	ValadocContentText * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, BALADOC_CONTENT_TYPE_TEXT, ValadocContentText);
	_g_free0 (self->priv->_content);
	G_OBJECT_CLASS (baladoc_content_text_parent_class)->finalize (obj);
}

static GType
baladoc_content_text_get_type_once (void)
{
	static const GTypeInfo g_define_type_info = { sizeof (ValadocContentTextClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) baladoc_content_text_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (ValadocContentText), 0, (GInstanceInitFunc) baladoc_content_text_instance_init, NULL };
	static const GInterfaceInfo baladoc_content_inline_info = { (GInterfaceInitFunc) baladoc_content_text_baladoc_content_inline_interface_init, (GInterfaceFinalizeFunc) NULL, NULL};
	GType baladoc_content_text_type_id;
	baladoc_content_text_type_id = g_type_register_static (BALADOC_CONTENT_TYPE_CONTENT_ELEMENT, "ValadocContentText", &g_define_type_info, 0);
	g_type_add_interface_static (baladoc_content_text_type_id, BALADOC_CONTENT_TYPE_INLINE, &baladoc_content_inline_info);
	ValadocContentText_private_offset = g_type_add_instance_private (baladoc_content_text_type_id, sizeof (ValadocContentTextPrivate));
	return baladoc_content_text_type_id;
}

GType
baladoc_content_text_get_type (void)
{
	static volatile gsize baladoc_content_text_type_id__volatile = 0;
	if (g_once_init_enter (&baladoc_content_text_type_id__volatile)) {
		GType baladoc_content_text_type_id;
		baladoc_content_text_type_id = baladoc_content_text_get_type_once ();
		g_once_init_leave (&baladoc_content_text_type_id__volatile, baladoc_content_text_type_id);
	}
	return baladoc_content_text_type_id__volatile;
}

static void
_bala_baladoc_content_text_get_property (GObject * object,
                                         guint property_id,
                                         GValue * value,
                                         GParamSpec * pspec)
{
	ValadocContentText * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, BALADOC_CONTENT_TYPE_TEXT, ValadocContentText);
	switch (property_id) {
		case BALADOC_CONTENT_TEXT_CONTENT_PROPERTY:
		g_value_set_string (value, baladoc_content_text_get_content (self));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

static void
_bala_baladoc_content_text_set_property (GObject * object,
                                         guint property_id,
                                         const GValue * value,
                                         GParamSpec * pspec)
{
	ValadocContentText * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (object, BALADOC_CONTENT_TYPE_TEXT, ValadocContentText);
	switch (property_id) {
		case BALADOC_CONTENT_TEXT_CONTENT_PROPERTY:
		baladoc_content_text_set_content (self, g_value_get_string (value));
		break;
		default:
		G_OBJECT_WARN_INVALID_PROPERTY_ID (object, property_id, pspec);
		break;
	}
}

